//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MailSendWPF.KMSPrivate {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://def.backend.ws.backend.kms.group.de", ConfigurationName="KMSPrivate.KMSBackendPrivateWebServicePortType")]
    public interface KMSBackendPrivateWebServicePortType {
        
        // CODEGEN: Generating message contract since the operation getServerVersion is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="urn:getServerVersion", ReplyAction="urn:getServerVersionResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        MailSendWPF.KMSPrivate.getServerVersionResponse getServerVersion(MailSendWPF.KMSPrivate.getServerVersionRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:getOrCreatePrivateKey", ReplyAction="urn:getOrCreatePrivateKeyResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        MailSendWPF.KMSPrivate.getOrCreatePrivateKeyResponse getOrCreatePrivateKey(MailSendWPF.KMSPrivate.getOrCreatePrivateKeyRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:getPrivateKeyBySerial", ReplyAction="urn:getPrivateKeyBySerialResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        MailSendWPF.KMSPrivate.getPrivateKeyBySerialResponse getPrivateKeyBySerial(MailSendWPF.KMSPrivate.getPrivateKeyBySerialRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:getOrCreatePrivateKeyAdvanced", ReplyAction="urn:getOrCreatePrivateKeyAdvancedResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        MailSendWPF.KMSPrivate.getOrCreatePrivateKeyAdvancedResponse getOrCreatePrivateKeyAdvanced(MailSendWPF.KMSPrivate.getOrCreatePrivateKeyAdvancedRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:downloadCertificates", ReplyAction="urn:downloadCertificatesResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        MailSendWPF.KMSPrivate.downloadCertificatesResponse downloadCertificates(MailSendWPF.KMSPrivate.downloadCertificatesRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:getCertificatesList", ReplyAction="urn:getCertificatesListResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        MailSendWPF.KMSPrivate.getCertificatesListResponse getCertificatesList(MailSendWPF.KMSPrivate.getCertificatesListRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:revokeCertificate", ReplyAction="urn:revokeCertificateResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        MailSendWPF.KMSPrivate.revokeCertificateResponse revokeCertificate(MailSendWPF.KMSPrivate.revokeCertificateRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:getAllPrivateKeysForEmail", ReplyAction="urn:getAllPrivateKeysForEmailResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        MailSendWPF.KMSPrivate.getAllPrivateKeysForEmailResponse getAllPrivateKeysForEmail(MailSendWPF.KMSPrivate.getAllPrivateKeysForEmailRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:getPrivateKey", ReplyAction="urn:getPrivateKeyResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        MailSendWPF.KMSPrivate.getPrivateKeyResponse getPrivateKey(MailSendWPF.KMSPrivate.getPrivateKeyRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:getPrivateKeyFromEnvelope", ReplyAction="urn:getPrivateKeyFromEnvelopeResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        MailSendWPF.KMSPrivate.getPrivateKeyFromEnvelopeResponse getPrivateKeyFromEnvelope(MailSendWPF.KMSPrivate.getPrivateKeyFromEnvelopeRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://def.backend.ws.backend.kms.group.de/xsd")]
    public partial class KMSVersion : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int buildField;
        
        private bool buildFieldSpecified;
        
        private int majorVersionField;
        
        private bool majorVersionFieldSpecified;
        
        private int minorVersionField;
        
        private bool minorVersionFieldSpecified;
        
        private string osField;
        
        private int revisionField;
        
        private bool revisionFieldSpecified;
        
        private int svnRevisionField;
        
        private bool svnRevisionFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int build {
            get {
                return this.buildField;
            }
            set {
                this.buildField = value;
                this.RaisePropertyChanged("build");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool buildSpecified {
            get {
                return this.buildFieldSpecified;
            }
            set {
                this.buildFieldSpecified = value;
                this.RaisePropertyChanged("buildSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int majorVersion {
            get {
                return this.majorVersionField;
            }
            set {
                this.majorVersionField = value;
                this.RaisePropertyChanged("majorVersion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool majorVersionSpecified {
            get {
                return this.majorVersionFieldSpecified;
            }
            set {
                this.majorVersionFieldSpecified = value;
                this.RaisePropertyChanged("majorVersionSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int minorVersion {
            get {
                return this.minorVersionField;
            }
            set {
                this.minorVersionField = value;
                this.RaisePropertyChanged("minorVersion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool minorVersionSpecified {
            get {
                return this.minorVersionFieldSpecified;
            }
            set {
                this.minorVersionFieldSpecified = value;
                this.RaisePropertyChanged("minorVersionSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string os {
            get {
                return this.osField;
            }
            set {
                this.osField = value;
                this.RaisePropertyChanged("os");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int revision {
            get {
                return this.revisionField;
            }
            set {
                this.revisionField = value;
                this.RaisePropertyChanged("revision");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool revisionSpecified {
            get {
                return this.revisionFieldSpecified;
            }
            set {
                this.revisionFieldSpecified = value;
                this.RaisePropertyChanged("revisionSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public int svnRevision {
            get {
                return this.svnRevisionField;
            }
            set {
                this.svnRevisionField = value;
                this.RaisePropertyChanged("svnRevision");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool svnRevisionSpecified {
            get {
                return this.svnRevisionFieldSpecified;
            }
            set {
                this.svnRevisionFieldSpecified = value;
                this.RaisePropertyChanged("svnRevisionSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://def.backend.ws.backend.kms.group.de/xsd")]
    public partial class CertificateInfoResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int certificateTypeField;
        
        private bool certificateTypeFieldSpecified;
        
        private string dataTypeField;
        
        private string hashIdField;
        
        private ReturnStatus retField;
        
        private string trustStatusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int certificateType {
            get {
                return this.certificateTypeField;
            }
            set {
                this.certificateTypeField = value;
                this.RaisePropertyChanged("certificateType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool certificateTypeSpecified {
            get {
                return this.certificateTypeFieldSpecified;
            }
            set {
                this.certificateTypeFieldSpecified = value;
                this.RaisePropertyChanged("certificateTypeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string dataType {
            get {
                return this.dataTypeField;
            }
            set {
                this.dataTypeField = value;
                this.RaisePropertyChanged("dataType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string hashId {
            get {
                return this.hashIdField;
            }
            set {
                this.hashIdField = value;
                this.RaisePropertyChanged("hashId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public ReturnStatus ret {
            get {
                return this.retField;
            }
            set {
                this.retField = value;
                this.RaisePropertyChanged("ret");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public string trustStatus {
            get {
                return this.trustStatusField;
            }
            set {
                this.trustStatusField = value;
                this.RaisePropertyChanged("trustStatus");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://def.backend.ws.backend.kms.group.de/xsd")]
    public partial class ReturnStatus : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string descriptionField;
        
        private int statusField;
        
        private bool statusFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("description");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool statusSpecified {
            get {
                return this.statusFieldSpecified;
            }
            set {
                this.statusFieldSpecified = value;
                this.RaisePropertyChanged("statusSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://def.backend.ws.backend.kms.group.de/xsd")]
    public partial class ArrayOfCertificateInfos : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long keysCountField;
        
        private bool keysCountFieldSpecified;
        
        private CertificateInfoResult[] listField;
        
        private ReturnStatus retField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long keysCount {
            get {
                return this.keysCountField;
            }
            set {
                this.keysCountField = value;
                this.RaisePropertyChanged("keysCount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool keysCountSpecified {
            get {
                return this.keysCountFieldSpecified;
            }
            set {
                this.keysCountFieldSpecified = value;
                this.RaisePropertyChanged("keysCountSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("list", IsNullable=true, Order=1)]
        public CertificateInfoResult[] list {
            get {
                return this.listField;
            }
            set {
                this.listField = value;
                this.RaisePropertyChanged("list");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public ReturnStatus ret {
            get {
                return this.retField;
            }
            set {
                this.retField = value;
                this.RaisePropertyChanged("ret");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://def.backend.ws.backend.kms.group.de/xsd")]
    public partial class ArrayOfKeys : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long keysCountField;
        
        private bool keysCountFieldSpecified;
        
        private KeyResult[] listField;
        
        private ReturnStatus retField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long keysCount {
            get {
                return this.keysCountField;
            }
            set {
                this.keysCountField = value;
                this.RaisePropertyChanged("keysCount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool keysCountSpecified {
            get {
                return this.keysCountFieldSpecified;
            }
            set {
                this.keysCountFieldSpecified = value;
                this.RaisePropertyChanged("keysCountSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("list", IsNullable=true, Order=1)]
        public KeyResult[] list {
            get {
                return this.listField;
            }
            set {
                this.listField = value;
                this.RaisePropertyChanged("list");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public ReturnStatus ret {
            get {
                return this.retField;
            }
            set {
                this.retField = value;
                this.RaisePropertyChanged("ret");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://def.backend.ws.backend.kms.group.de/xsd")]
    public partial class KeyResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private byte[] dataField;
        
        private string dataTypeField;
        
        private string keyPasswordField;
        
        private ReturnStatus retField;
        
        private string trustStatusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", IsNullable=true, Order=0)]
        public byte[] data {
            get {
                return this.dataField;
            }
            set {
                this.dataField = value;
                this.RaisePropertyChanged("data");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string dataType {
            get {
                return this.dataTypeField;
            }
            set {
                this.dataTypeField = value;
                this.RaisePropertyChanged("dataType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string keyPassword {
            get {
                return this.keyPasswordField;
            }
            set {
                this.keyPasswordField = value;
                this.RaisePropertyChanged("keyPassword");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public ReturnStatus ret {
            get {
                return this.retField;
            }
            set {
                this.retField = value;
                this.RaisePropertyChanged("ret");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public string trustStatus {
            get {
                return this.trustStatusField;
            }
            set {
                this.trustStatusField = value;
                this.RaisePropertyChanged("trustStatus");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://def.backend.ws.backend.kms.group.de/xsd")]
    public partial class CertificateData : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string challengeField;
        
        private string commentField;
        
        private string countryField;
        
        private string firstNameField;
        
        private string[] keysField;
        
        private string lastNameField;
        
        private string localityField;
        
        private string organizationField;
        
        private string organizationUnitField;
        
        private string stateField;
        
        private string titleField;
        
        private string[] valuesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string challenge {
            get {
                return this.challengeField;
            }
            set {
                this.challengeField = value;
                this.RaisePropertyChanged("challenge");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string comment {
            get {
                return this.commentField;
            }
            set {
                this.commentField = value;
                this.RaisePropertyChanged("comment");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string country {
            get {
                return this.countryField;
            }
            set {
                this.countryField = value;
                this.RaisePropertyChanged("country");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string firstName {
            get {
                return this.firstNameField;
            }
            set {
                this.firstNameField = value;
                this.RaisePropertyChanged("firstName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("keys", IsNullable=true, Order=4)]
        public string[] keys {
            get {
                return this.keysField;
            }
            set {
                this.keysField = value;
                this.RaisePropertyChanged("keys");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public string lastName {
            get {
                return this.lastNameField;
            }
            set {
                this.lastNameField = value;
                this.RaisePropertyChanged("lastName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public string locality {
            get {
                return this.localityField;
            }
            set {
                this.localityField = value;
                this.RaisePropertyChanged("locality");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=7)]
        public string organization {
            get {
                return this.organizationField;
            }
            set {
                this.organizationField = value;
                this.RaisePropertyChanged("organization");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=8)]
        public string organizationUnit {
            get {
                return this.organizationUnitField;
            }
            set {
                this.organizationUnitField = value;
                this.RaisePropertyChanged("organizationUnit");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=9)]
        public string state {
            get {
                return this.stateField;
            }
            set {
                this.stateField = value;
                this.RaisePropertyChanged("state");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=10)]
        public string title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
                this.RaisePropertyChanged("title");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("values", IsNullable=true, Order=11)]
        public string[] values {
            get {
                return this.valuesField;
            }
            set {
                this.valuesField = value;
                this.RaisePropertyChanged("values");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getServerVersionRequest {
        
        public getServerVersionRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getServerVersionResponse", WrapperNamespace="http://def.backend.ws.backend.kms.group.de", IsWrapped=true)]
    public partial class getServerVersionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://def.backend.ws.backend.kms.group.de", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public MailSendWPF.KMSPrivate.KMSVersion @return;
        
        public getServerVersionResponse() {
        }
        
        public getServerVersionResponse(MailSendWPF.KMSPrivate.KMSVersion @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getOrCreatePrivateKey", WrapperNamespace="http://def.backend.ws.backend.kms.group.de", IsWrapped=true)]
    public partial class getOrCreatePrivateKeyRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://def.backend.ws.backend.kms.group.de", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string guid;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://def.backend.ws.backend.kms.group.de", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string emailAddress;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://def.backend.ws.backend.kms.group.de", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public MailSendWPF.KMSPrivate.CertificateData data;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://def.backend.ws.backend.kms.group.de", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string outputKeyType;
        
        public getOrCreatePrivateKeyRequest() {
        }
        
        public getOrCreatePrivateKeyRequest(string guid, string emailAddress, MailSendWPF.KMSPrivate.CertificateData data, string outputKeyType) {
            this.guid = guid;
            this.emailAddress = emailAddress;
            this.data = data;
            this.outputKeyType = outputKeyType;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getOrCreatePrivateKeyResponse", WrapperNamespace="http://def.backend.ws.backend.kms.group.de", IsWrapped=true)]
    public partial class getOrCreatePrivateKeyResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://def.backend.ws.backend.kms.group.de", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public MailSendWPF.KMSPrivate.KeyResult @return;
        
        public getOrCreatePrivateKeyResponse() {
        }
        
        public getOrCreatePrivateKeyResponse(MailSendWPF.KMSPrivate.KeyResult @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getPrivateKeyBySerial", WrapperNamespace="http://def.backend.ws.backend.kms.group.de", IsWrapped=true)]
    public partial class getPrivateKeyBySerialRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://def.backend.ws.backend.kms.group.de", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string guid;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://def.backend.ws.backend.kms.group.de", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string issuerDN;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://def.backend.ws.backend.kms.group.de", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string serial;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://def.backend.ws.backend.kms.group.de", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string outputKeyType;
        
        public getPrivateKeyBySerialRequest() {
        }
        
        public getPrivateKeyBySerialRequest(string guid, string issuerDN, string serial, string outputKeyType) {
            this.guid = guid;
            this.issuerDN = issuerDN;
            this.serial = serial;
            this.outputKeyType = outputKeyType;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getPrivateKeyBySerialResponse", WrapperNamespace="http://def.backend.ws.backend.kms.group.de", IsWrapped=true)]
    public partial class getPrivateKeyBySerialResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://def.backend.ws.backend.kms.group.de", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public MailSendWPF.KMSPrivate.KeyResult @return;
        
        public getPrivateKeyBySerialResponse() {
        }
        
        public getPrivateKeyBySerialResponse(MailSendWPF.KMSPrivate.KeyResult @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getOrCreatePrivateKeyAdvanced", WrapperNamespace="http://def.backend.ws.backend.kms.group.de", IsWrapped=true)]
    public partial class getOrCreatePrivateKeyAdvancedRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://def.backend.ws.backend.kms.group.de", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string guid;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://def.backend.ws.backend.kms.group.de", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string emailAddress;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://def.backend.ws.backend.kms.group.de", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute("keys", IsNullable=true)]
        public string[] keys;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://def.backend.ws.backend.kms.group.de", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute("values", IsNullable=true)]
        public string[] values;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://def.backend.ws.backend.kms.group.de", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string outputKeyType;
        
        public getOrCreatePrivateKeyAdvancedRequest() {
        }
        
        public getOrCreatePrivateKeyAdvancedRequest(string guid, string emailAddress, string[] keys, string[] values, string outputKeyType) {
            this.guid = guid;
            this.emailAddress = emailAddress;
            this.keys = keys;
            this.values = values;
            this.outputKeyType = outputKeyType;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getOrCreatePrivateKeyAdvancedResponse", WrapperNamespace="http://def.backend.ws.backend.kms.group.de", IsWrapped=true)]
    public partial class getOrCreatePrivateKeyAdvancedResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://def.backend.ws.backend.kms.group.de", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public MailSendWPF.KMSPrivate.KeyResult @return;
        
        public getOrCreatePrivateKeyAdvancedResponse() {
        }
        
        public getOrCreatePrivateKeyAdvancedResponse(MailSendWPF.KMSPrivate.KeyResult @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="downloadCertificates", WrapperNamespace="http://def.backend.ws.backend.kms.group.de", IsWrapped=true)]
    public partial class downloadCertificatesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://def.backend.ws.backend.kms.group.de", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string tenantGuid;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://def.backend.ws.backend.kms.group.de", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute("hashIds", IsNullable=true)]
        public string[] hashIds;
        
        public downloadCertificatesRequest() {
        }
        
        public downloadCertificatesRequest(string tenantGuid, string[] hashIds) {
            this.tenantGuid = tenantGuid;
            this.hashIds = hashIds;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="downloadCertificatesResponse", WrapperNamespace="http://def.backend.ws.backend.kms.group.de", IsWrapped=true)]
    public partial class downloadCertificatesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://def.backend.ws.backend.kms.group.de", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public MailSendWPF.KMSPrivate.ArrayOfKeys @return;
        
        public downloadCertificatesResponse() {
        }
        
        public downloadCertificatesResponse(MailSendWPF.KMSPrivate.ArrayOfKeys @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getCertificatesList", WrapperNamespace="http://def.backend.ws.backend.kms.group.de", IsWrapped=true)]
    public partial class getCertificatesListRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://def.backend.ws.backend.kms.group.de", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string tenantGuid;
        
        public getCertificatesListRequest() {
        }
        
        public getCertificatesListRequest(string tenantGuid) {
            this.tenantGuid = tenantGuid;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getCertificatesListResponse", WrapperNamespace="http://def.backend.ws.backend.kms.group.de", IsWrapped=true)]
    public partial class getCertificatesListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://def.backend.ws.backend.kms.group.de", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public MailSendWPF.KMSPrivate.ArrayOfCertificateInfos @return;
        
        public getCertificatesListResponse() {
        }
        
        public getCertificatesListResponse(MailSendWPF.KMSPrivate.ArrayOfCertificateInfos @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="revokeCertificate", WrapperNamespace="http://def.backend.ws.backend.kms.group.de", IsWrapped=true)]
    public partial class revokeCertificateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://def.backend.ws.backend.kms.group.de", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string guid;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://def.backend.ws.backend.kms.group.de", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string issuerDN;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://def.backend.ws.backend.kms.group.de", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string serialNo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://def.backend.ws.backend.kms.group.de", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string emailAddress;
        
        public revokeCertificateRequest() {
        }
        
        public revokeCertificateRequest(string guid, string issuerDN, string serialNo, string emailAddress) {
            this.guid = guid;
            this.issuerDN = issuerDN;
            this.serialNo = serialNo;
            this.emailAddress = emailAddress;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="revokeCertificateResponse", WrapperNamespace="http://def.backend.ws.backend.kms.group.de", IsWrapped=true)]
    public partial class revokeCertificateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://def.backend.ws.backend.kms.group.de", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public MailSendWPF.KMSPrivate.KeyResult @return;
        
        public revokeCertificateResponse() {
        }
        
        public revokeCertificateResponse(MailSendWPF.KMSPrivate.KeyResult @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAllPrivateKeysForEmail", WrapperNamespace="http://def.backend.ws.backend.kms.group.de", IsWrapped=true)]
    public partial class getAllPrivateKeysForEmailRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://def.backend.ws.backend.kms.group.de", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string guid;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://def.backend.ws.backend.kms.group.de", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string emailAddress;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://def.backend.ws.backend.kms.group.de", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string outputKeyType;
        
        public getAllPrivateKeysForEmailRequest() {
        }
        
        public getAllPrivateKeysForEmailRequest(string guid, string emailAddress, string outputKeyType) {
            this.guid = guid;
            this.emailAddress = emailAddress;
            this.outputKeyType = outputKeyType;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAllPrivateKeysForEmailResponse", WrapperNamespace="http://def.backend.ws.backend.kms.group.de", IsWrapped=true)]
    public partial class getAllPrivateKeysForEmailResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://def.backend.ws.backend.kms.group.de", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public MailSendWPF.KMSPrivate.ArrayOfKeys @return;
        
        public getAllPrivateKeysForEmailResponse() {
        }
        
        public getAllPrivateKeysForEmailResponse(MailSendWPF.KMSPrivate.ArrayOfKeys @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getPrivateKey", WrapperNamespace="http://def.backend.ws.backend.kms.group.de", IsWrapped=true)]
    public partial class getPrivateKeyRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://def.backend.ws.backend.kms.group.de", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string guid;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://def.backend.ws.backend.kms.group.de", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string emailAddress;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://def.backend.ws.backend.kms.group.de", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string outputKeyType;
        
        public getPrivateKeyRequest() {
        }
        
        public getPrivateKeyRequest(string guid, string emailAddress, string outputKeyType) {
            this.guid = guid;
            this.emailAddress = emailAddress;
            this.outputKeyType = outputKeyType;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getPrivateKeyResponse", WrapperNamespace="http://def.backend.ws.backend.kms.group.de", IsWrapped=true)]
    public partial class getPrivateKeyResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://def.backend.ws.backend.kms.group.de", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public MailSendWPF.KMSPrivate.KeyResult @return;
        
        public getPrivateKeyResponse() {
        }
        
        public getPrivateKeyResponse(MailSendWPF.KMSPrivate.KeyResult @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getPrivateKeyFromEnvelope", WrapperNamespace="http://def.backend.ws.backend.kms.group.de", IsWrapped=true)]
    public partial class getPrivateKeyFromEnvelopeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://def.backend.ws.backend.kms.group.de", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string guid;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://def.backend.ws.backend.kms.group.de", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", IsNullable=true)]
        public byte[] envelopData;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://def.backend.ws.backend.kms.group.de", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string outputKeyType;
        
        public getPrivateKeyFromEnvelopeRequest() {
        }
        
        public getPrivateKeyFromEnvelopeRequest(string guid, byte[] envelopData, string outputKeyType) {
            this.guid = guid;
            this.envelopData = envelopData;
            this.outputKeyType = outputKeyType;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getPrivateKeyFromEnvelopeResponse", WrapperNamespace="http://def.backend.ws.backend.kms.group.de", IsWrapped=true)]
    public partial class getPrivateKeyFromEnvelopeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://def.backend.ws.backend.kms.group.de", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public MailSendWPF.KMSPrivate.KeyResult @return;
        
        public getPrivateKeyFromEnvelopeResponse() {
        }
        
        public getPrivateKeyFromEnvelopeResponse(MailSendWPF.KMSPrivate.KeyResult @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface KMSBackendPrivateWebServicePortTypeChannel : MailSendWPF.KMSPrivate.KMSBackendPrivateWebServicePortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class KMSBackendPrivateWebServicePortTypeClient : System.ServiceModel.ClientBase<MailSendWPF.KMSPrivate.KMSBackendPrivateWebServicePortType>, MailSendWPF.KMSPrivate.KMSBackendPrivateWebServicePortType {
        
        public KMSBackendPrivateWebServicePortTypeClient() {
        }
        
        public KMSBackendPrivateWebServicePortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public KMSBackendPrivateWebServicePortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public KMSBackendPrivateWebServicePortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public KMSBackendPrivateWebServicePortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MailSendWPF.KMSPrivate.getServerVersionResponse MailSendWPF.KMSPrivate.KMSBackendPrivateWebServicePortType.getServerVersion(MailSendWPF.KMSPrivate.getServerVersionRequest request) {
            return base.Channel.getServerVersion(request);
        }
        
        public MailSendWPF.KMSPrivate.KMSVersion getServerVersion() {
            MailSendWPF.KMSPrivate.getServerVersionRequest inValue = new MailSendWPF.KMSPrivate.getServerVersionRequest();
            MailSendWPF.KMSPrivate.getServerVersionResponse retVal = ((MailSendWPF.KMSPrivate.KMSBackendPrivateWebServicePortType)(this)).getServerVersion(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MailSendWPF.KMSPrivate.getOrCreatePrivateKeyResponse MailSendWPF.KMSPrivate.KMSBackendPrivateWebServicePortType.getOrCreatePrivateKey(MailSendWPF.KMSPrivate.getOrCreatePrivateKeyRequest request) {
            return base.Channel.getOrCreatePrivateKey(request);
        }
        
        public MailSendWPF.KMSPrivate.KeyResult getOrCreatePrivateKey(string guid, string emailAddress, MailSendWPF.KMSPrivate.CertificateData data, string outputKeyType) {
            MailSendWPF.KMSPrivate.getOrCreatePrivateKeyRequest inValue = new MailSendWPF.KMSPrivate.getOrCreatePrivateKeyRequest();
            inValue.guid = guid;
            inValue.emailAddress = emailAddress;
            inValue.data = data;
            inValue.outputKeyType = outputKeyType;
            MailSendWPF.KMSPrivate.getOrCreatePrivateKeyResponse retVal = ((MailSendWPF.KMSPrivate.KMSBackendPrivateWebServicePortType)(this)).getOrCreatePrivateKey(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MailSendWPF.KMSPrivate.getPrivateKeyBySerialResponse MailSendWPF.KMSPrivate.KMSBackendPrivateWebServicePortType.getPrivateKeyBySerial(MailSendWPF.KMSPrivate.getPrivateKeyBySerialRequest request) {
            return base.Channel.getPrivateKeyBySerial(request);
        }
        
        public MailSendWPF.KMSPrivate.KeyResult getPrivateKeyBySerial(string guid, string issuerDN, string serial, string outputKeyType) {
            MailSendWPF.KMSPrivate.getPrivateKeyBySerialRequest inValue = new MailSendWPF.KMSPrivate.getPrivateKeyBySerialRequest();
            inValue.guid = guid;
            inValue.issuerDN = issuerDN;
            inValue.serial = serial;
            inValue.outputKeyType = outputKeyType;
            MailSendWPF.KMSPrivate.getPrivateKeyBySerialResponse retVal = ((MailSendWPF.KMSPrivate.KMSBackendPrivateWebServicePortType)(this)).getPrivateKeyBySerial(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MailSendWPF.KMSPrivate.getOrCreatePrivateKeyAdvancedResponse MailSendWPF.KMSPrivate.KMSBackendPrivateWebServicePortType.getOrCreatePrivateKeyAdvanced(MailSendWPF.KMSPrivate.getOrCreatePrivateKeyAdvancedRequest request) {
            return base.Channel.getOrCreatePrivateKeyAdvanced(request);
        }
        
        public MailSendWPF.KMSPrivate.KeyResult getOrCreatePrivateKeyAdvanced(string guid, string emailAddress, string[] keys, string[] values, string outputKeyType) {
            MailSendWPF.KMSPrivate.getOrCreatePrivateKeyAdvancedRequest inValue = new MailSendWPF.KMSPrivate.getOrCreatePrivateKeyAdvancedRequest();
            inValue.guid = guid;
            inValue.emailAddress = emailAddress;
            inValue.keys = keys;
            inValue.values = values;
            inValue.outputKeyType = outputKeyType;
            MailSendWPF.KMSPrivate.getOrCreatePrivateKeyAdvancedResponse retVal = ((MailSendWPF.KMSPrivate.KMSBackendPrivateWebServicePortType)(this)).getOrCreatePrivateKeyAdvanced(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MailSendWPF.KMSPrivate.downloadCertificatesResponse MailSendWPF.KMSPrivate.KMSBackendPrivateWebServicePortType.downloadCertificates(MailSendWPF.KMSPrivate.downloadCertificatesRequest request) {
            return base.Channel.downloadCertificates(request);
        }
        
        public MailSendWPF.KMSPrivate.ArrayOfKeys downloadCertificates(string tenantGuid, string[] hashIds) {
            MailSendWPF.KMSPrivate.downloadCertificatesRequest inValue = new MailSendWPF.KMSPrivate.downloadCertificatesRequest();
            inValue.tenantGuid = tenantGuid;
            inValue.hashIds = hashIds;
            MailSendWPF.KMSPrivate.downloadCertificatesResponse retVal = ((MailSendWPF.KMSPrivate.KMSBackendPrivateWebServicePortType)(this)).downloadCertificates(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MailSendWPF.KMSPrivate.getCertificatesListResponse MailSendWPF.KMSPrivate.KMSBackendPrivateWebServicePortType.getCertificatesList(MailSendWPF.KMSPrivate.getCertificatesListRequest request) {
            return base.Channel.getCertificatesList(request);
        }
        
        public MailSendWPF.KMSPrivate.ArrayOfCertificateInfos getCertificatesList(string tenantGuid) {
            MailSendWPF.KMSPrivate.getCertificatesListRequest inValue = new MailSendWPF.KMSPrivate.getCertificatesListRequest();
            inValue.tenantGuid = tenantGuid;
            MailSendWPF.KMSPrivate.getCertificatesListResponse retVal = ((MailSendWPF.KMSPrivate.KMSBackendPrivateWebServicePortType)(this)).getCertificatesList(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MailSendWPF.KMSPrivate.revokeCertificateResponse MailSendWPF.KMSPrivate.KMSBackendPrivateWebServicePortType.revokeCertificate(MailSendWPF.KMSPrivate.revokeCertificateRequest request) {
            return base.Channel.revokeCertificate(request);
        }
        
        public MailSendWPF.KMSPrivate.KeyResult revokeCertificate(string guid, string issuerDN, string serialNo, string emailAddress) {
            MailSendWPF.KMSPrivate.revokeCertificateRequest inValue = new MailSendWPF.KMSPrivate.revokeCertificateRequest();
            inValue.guid = guid;
            inValue.issuerDN = issuerDN;
            inValue.serialNo = serialNo;
            inValue.emailAddress = emailAddress;
            MailSendWPF.KMSPrivate.revokeCertificateResponse retVal = ((MailSendWPF.KMSPrivate.KMSBackendPrivateWebServicePortType)(this)).revokeCertificate(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MailSendWPF.KMSPrivate.getAllPrivateKeysForEmailResponse MailSendWPF.KMSPrivate.KMSBackendPrivateWebServicePortType.getAllPrivateKeysForEmail(MailSendWPF.KMSPrivate.getAllPrivateKeysForEmailRequest request) {
            return base.Channel.getAllPrivateKeysForEmail(request);
        }
        
        public MailSendWPF.KMSPrivate.ArrayOfKeys getAllPrivateKeysForEmail(string guid, string emailAddress, string outputKeyType) {
            MailSendWPF.KMSPrivate.getAllPrivateKeysForEmailRequest inValue = new MailSendWPF.KMSPrivate.getAllPrivateKeysForEmailRequest();
            inValue.guid = guid;
            inValue.emailAddress = emailAddress;
            inValue.outputKeyType = outputKeyType;
            MailSendWPF.KMSPrivate.getAllPrivateKeysForEmailResponse retVal = ((MailSendWPF.KMSPrivate.KMSBackendPrivateWebServicePortType)(this)).getAllPrivateKeysForEmail(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MailSendWPF.KMSPrivate.getPrivateKeyResponse MailSendWPF.KMSPrivate.KMSBackendPrivateWebServicePortType.getPrivateKey(MailSendWPF.KMSPrivate.getPrivateKeyRequest request) {
            return base.Channel.getPrivateKey(request);
        }
        
        public MailSendWPF.KMSPrivate.KeyResult getPrivateKey(string guid, string emailAddress, string outputKeyType) {
            MailSendWPF.KMSPrivate.getPrivateKeyRequest inValue = new MailSendWPF.KMSPrivate.getPrivateKeyRequest();
            inValue.guid = guid;
            inValue.emailAddress = emailAddress;
            inValue.outputKeyType = outputKeyType;
            MailSendWPF.KMSPrivate.getPrivateKeyResponse retVal = ((MailSendWPF.KMSPrivate.KMSBackendPrivateWebServicePortType)(this)).getPrivateKey(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MailSendWPF.KMSPrivate.getPrivateKeyFromEnvelopeResponse MailSendWPF.KMSPrivate.KMSBackendPrivateWebServicePortType.getPrivateKeyFromEnvelope(MailSendWPF.KMSPrivate.getPrivateKeyFromEnvelopeRequest request) {
            return base.Channel.getPrivateKeyFromEnvelope(request);
        }
        
        public MailSendWPF.KMSPrivate.KeyResult getPrivateKeyFromEnvelope(string guid, byte[] envelopData, string outputKeyType) {
            MailSendWPF.KMSPrivate.getPrivateKeyFromEnvelopeRequest inValue = new MailSendWPF.KMSPrivate.getPrivateKeyFromEnvelopeRequest();
            inValue.guid = guid;
            inValue.envelopData = envelopData;
            inValue.outputKeyType = outputKeyType;
            MailSendWPF.KMSPrivate.getPrivateKeyFromEnvelopeResponse retVal = ((MailSendWPF.KMSPrivate.KMSBackendPrivateWebServicePortType)(this)).getPrivateKeyFromEnvelope(inValue);
            return retVal.@return;
        }
    }
}
