//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MetaBuilders.WebControls {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ValidatorScripts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ValidatorScripts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MetaBuilders.WebControls.ValidatorScripts", typeof(ValidatorScripts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;script type=&quot;text/vbscript&quot;&gt;
        ///Function MetaBuilders_CurrencyValidator_CheckValue(value)
        ///	On Error Resume Next
        ///	Dim tempVar
        ///	tempVar = CCur(value)
        ///	If Err Then
        ///		MetaBuilders_CurrencyValidator_CheckValue= False
        ///	Else
        ///		MetaBuilders_CurrencyValidator_CheckValue= True
        ///	End If
        ///End Function
        ///&lt;/script&gt;
        ///&lt;script type=&quot;text/javascript&quot;&gt;
        ///function MetaBuilders_CurrencyValidatorEvaluateIsValid(val) {
        ///	var value = ValidatorGetValue(val.controltovalidate);
        ///	if (ValidatorTrim(value).length == 0)
        ///		return tr [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CurrencyValidator_Script {
            get {
                return ResourceManager.GetString("CurrencyValidator_Script", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;script language=&quot;VBScript&quot;&gt;
        ///Function MetaBuilders_DateTimeValidator_CheckValue(value)
        ///	MetaBuilders_DateTimeValidator_CheckValue= IsDate(value)
        ///End Function
        ///&lt;/script&gt;
        ///&lt;script language=&quot;javascript&quot;&gt;
        ///function MetaBuilders_DateTimeValidatorEvaluateIsValid(val) {
        ///	var value = ValidatorGetValue(val.controltovalidate);
        ///	if (ValidatorTrim(value).length == 0)
        ///		return true;        
        ///	return MetaBuilders_DateTimeValidator_CheckValue(value);
        ///}
        ///&lt;/script&gt;.
        /// </summary>
        internal static string DateTimeValidator_Script {
            get {
                return ResourceManager.GetString("DateTimeValidator_Script", resourceCulture);
            }
        }
    }
}
