//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MetaBuilders.WebControls {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MetaBuilders.WebControls.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not create Access database file at path &apos;(0}&apos;. Make sure the asp.net user has read/write permissions to this folder..
        /// </summary>
        internal static string AccessProvider_CantCreateFile {
            get {
                return ResourceManager.GetString("AccessProvider_CantCreateFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not locate the Access database resource to copy to the data folder. Copy the file manually..
        /// </summary>
        internal static string AccessProvider_MissingAccessDatabaseResource {
            get {
                return ResourceManager.GetString("AccessProvider_MissingAccessDatabaseResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AdSenseAdUnitDesigner can only be used with AdSenseAsUnit controls..
        /// </summary>
        internal static string AdSenseAdUnitDesigner_InvalidComponent {
            get {
                return ResourceManager.GetString("AdSenseAdUnitDesigner_InvalidComponent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AdSenseLinkUnitDesigner can only be used with AdSenseLinkUnit controls..
        /// </summary>
        internal static string AdSenseLinkUnitDesigner_InvalidComponent {
            get {
                return ResourceManager.GetString("AdSenseLinkUnitDesigner_InvalidComponent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to if ( typeof(Sys) != &apos;undefined&apos; ) {{ Sys.WebForms.PageRequestManager.getInstance().add_endRequest({0}); }}.
        /// </summary>
        internal static string AjaxWorkaroundScript {
            get {
                return ResourceManager.GetString("AjaxWorkaroundScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BooleanSelectionMode.CheckBox does not support null values..
        /// </summary>
        internal static string BooleanField_CheckBoxNotNull {
            get {
                return ResourceManager.GetString("BooleanField_CheckBoxNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Design Time.
        /// </summary>
        internal static string Category_DesignTime {
            get {
                return ResourceManager.GetString("Category_DesignTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dialog.
        /// </summary>
        internal static string Category_Dialog {
            get {
                return ResourceManager.GetString("Category_Dialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Google.
        /// </summary>
        internal static string Category_Google {
            get {
                return ResourceManager.GetString("Category_Google", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ListBox Appearance.
        /// </summary>
        internal static string Category_ListBoxAppearance {
            get {
                return ResourceManager.GetString("Category_ListBoxAppearance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RadioButton Appearance.
        /// </summary>
        internal static string Category_RadioButtonsAppearance {
            get {
                return ResourceManager.GetString("Category_RadioButtonsAppearance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Window Attributes.
        /// </summary>
        internal static string Category_WindowAttributes {
            get {
                return ResourceManager.GetString("Category_WindowAttributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show List.
        /// </summary>
        internal static string ComboBox_DefaultAltText {
            get {
                return ResourceManager.GetString("ComboBox_DefaultAltText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CommandName cannot be null..
        /// </summary>
        internal static string CommandNameCannotBeNull {
            get {
                return ResourceManager.GetString("CommandNameCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CommandName &apos;{0}&apos; does not match expected CommandName &apos;{1}&apos;..
        /// </summary>
        internal static string CommandNamesDoNotMatch {
            get {
                return ResourceManager.GetString("CommandNamesDoNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provider you were attempting to add, already exists..
        /// </summary>
        internal static string Config_AddExists {
            get {
                return ResourceManager.GetString("Config_AddExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only &apos;add&apos;, &apos;remove&apos;, and &apos;clear&apos; elements are allow in the &apos;providers&apos; element..
        /// </summary>
        internal static string Config_AddRemoveClearOnly {
            get {
                return ResourceManager.GetString("Config_AddRemoveClearOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;{0}&apos; attribute is required to be either &apos;true&apos; or &apos;false&apos;..
        /// </summary>
        internal static string Config_AttributeNotBoolean {
            get {
                return ResourceManager.GetString("Config_AttributeNotBoolean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;{0}&apos; attribute is required..
        /// </summary>
        internal static string Config_AttributeRequired {
            get {
                return ResourceManager.GetString("Config_AttributeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The MetaBuilders Polling feature requires configuration modifications that were not found. This change configures the provider the Polling uses to store data..
        /// </summary>
        internal static string Config_ConfigCannotBeFound {
            get {
                return ResourceManager.GetString("Config_ConfigCannotBeFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The connection string named &apos;{0}&apos; was not found in the application&apos;s configuration or the connection string is empty..
        /// </summary>
        internal static string Config_ConnectionStringNameNotFound {
            get {
                return ResourceManager.GetString("Config_ConnectionStringNameNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database connection string name not found. The {0} provider requires a connection string to its database. This is set in &apos;polling/providers&apos; section of web.config as an attribute named &apos;connectionStringName&apos; on the &apos;add&apos; element. The value of this attribute will refer to the name of an item in the &apos;appSettings&apos; section of web.config that contains the connection string..
        /// </summary>
        internal static string Config_ConnectionStringNamePropertyRequired {
            get {
                return ResourceManager.GetString("Config_ConnectionStringNamePropertyRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Polling provider &apos;{0}&apos; specified in web.config as the default provider, does not match any of the configured providers..
        /// </summary>
        internal static string Config_InvalidDefaultProvider {
            get {
                return ResourceManager.GetString("Config_InvalidDefaultProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The data source path is invalid in the connection string &apos;{0}&apos;..
        /// </summary>
        internal static string Config_InvalidPathInConnectionString {
            get {
                return ResourceManager.GetString("Config_InvalidPathInConnectionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Polling provider named &apos;{0}&apos;, specified in web.config, is not a valid provider..
        /// </summary>
        internal static string Config_InvalidProvider {
            get {
                return ResourceManager.GetString("Config_InvalidProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Polling configuration in web.config did not contain any providers. At least one provider must be specified..
        /// </summary>
        internal static string Config_NoProviders {
            get {
                return ResourceManager.GetString("Config_NoProviders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only &apos;provider&apos; elements are allowed inside the &apos;polling&apos; element..
        /// </summary>
        internal static string Config_ProvidersOnly {
            get {
                return ResourceManager.GetString("Config_ProvidersOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;remove&apos; element requires a name attribute..
        /// </summary>
        internal static string Config_RemoveRequiresName {
            get {
                return ResourceManager.GetString("Config_RemoveRequiresName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;{0}&apos; attribute is unknown..
        /// </summary>
        internal static string Config_UnknownAttribute {
            get {
                return ResourceManager.GetString("Config_UnknownAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified provider, &apos;{0}&apos;, cannot be found..
        /// </summary>
        internal static string Config_UnknownProvider {
            get {
                return ResourceManager.GetString("Config_UnknownProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control &apos;{0}&apos; not found..
        /// </summary>
        internal static string ControlCannotBeFound {
            get {
                return ResourceManager.GetString("ControlCannotBeFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataBound.
        /// </summary>
        internal static string DataBound {
            get {
                return ResourceManager.GetString("DataBound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item must be a DefaultButtonSetting.
        /// </summary>
        internal static string DefaultButtons_ItemMustBeSetting {
            get {
                return ResourceManager.GetString("DefaultButtons_ItemMustBeSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more settings are invalid for DefaultButtons control {0}..
        /// </summary>
        internal static string DefaultButtons_SettingsInvalid {
            get {
                return ResourceManager.GetString("DefaultButtons_SettingsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string DialogWindow_Cancel {
            get {
                return ResourceManager.GetString("DialogWindow_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find a DialogWindow with the name &apos;{0}&apos;..
        /// </summary>
        internal static string DialogWindow_CannotFindDialogWindow {
            get {
                return ResourceManager.GetString("DialogWindow_CannotFindDialogWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to    NO   .
        /// </summary>
        internal static string DialogWindow_NoSpaced {
            get {
                return ResourceManager.GetString("DialogWindow_NoSpaced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string DialogWindow_OK {
            get {
                return ResourceManager.GetString("DialogWindow_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to    OK   .
        /// </summary>
        internal static string DialogWindow_OKSpaced {
            get {
                return ResourceManager.GetString("DialogWindow_OKSpaced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Retry .
        /// </summary>
        internal static string DialogWindow_RetrySpaced {
            get {
                return ResourceManager.GetString("DialogWindow_RetrySpaced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   Yes   .
        /// </summary>
        internal static string DialogWindow_YesSpaced {
            get {
                return ResourceManager.GetString("DialogWindow_YesSpaced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add All -&gt;&gt;.
        /// </summary>
        internal static string DualList_AddAll {
            get {
                return ResourceManager.GetString("DualList_AddAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add -&gt;.
        /// </summary>
        internal static string DualList_AddItem {
            get {
                return ResourceManager.GetString("DualList_AddItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available Items.
        /// </summary>
        internal static string DualList_AvailableItems {
            get {
                return ResourceManager.GetString("DualList_AvailableItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chosen Items.
        /// </summary>
        internal static string DualList_ChosenItems {
            get {
                return ResourceManager.GetString("DualList_ChosenItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Left Items....
        /// </summary>
        internal static string DualList_EditLeftItems {
            get {
                return ResourceManager.GetString("DualList_EditLeftItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit the items visible in the left list.
        /// </summary>
        internal static string DualList_EditLeftItemsEffectDescription {
            get {
                return ResourceManager.GetString("DualList_EditLeftItemsEffectDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Right Items....
        /// </summary>
        internal static string DualList_EditRightItems {
            get {
                return ResourceManager.GetString("DualList_EditRightItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit the items visible in the right list.
        /// </summary>
        internal static string DualList_EditRightItemsEffectDescription {
            get {
                return ResourceManager.GetString("DualList_EditRightItemsEffectDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Down.
        /// </summary>
        internal static string DualList_MoveDown {
            get {
                return ResourceManager.GetString("DualList_MoveDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Up.
        /// </summary>
        internal static string DualList_MoveUp {
            get {
                return ResourceManager.GetString("DualList_MoveUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;&lt;- Remove All.
        /// </summary>
        internal static string DualList_RemoveAll {
            get {
                return ResourceManager.GetString("DualList_RemoveAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;- Remove.
        /// </summary>
        internal static string DualList_RemoveItem {
            get {
                return ResourceManager.GetString("DualList_RemoveItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle EnableMoveAll.
        /// </summary>
        internal static string DualList_ToggleEnableMoveAll {
            get {
                return ResourceManager.GetString("DualList_ToggleEnableMoveAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggles the visibility of the buttons which move all items.
        /// </summary>
        internal static string DualList_ToggleEnableMoveAllDescription {
            get {
                return ResourceManager.GetString("DualList_ToggleEnableMoveAllDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle EnableMoveUpDown.
        /// </summary>
        internal static string DualList_ToggleEnableMoveUpDown {
            get {
                return ResourceManager.GetString("DualList_ToggleEnableMoveUpDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggles the visibility of the buttons which move chosen items up and down.
        /// </summary>
        internal static string DualList_ToggleEnableMoveUpDownDescription {
            get {
                return ResourceManager.GetString("DualList_ToggleEnableMoveUpDownDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ContractionControl must be set..
        /// </summary>
        internal static string ExpandingPanel_ContractionControlMustBeSet {
            get {
                return ResourceManager.GetString("ExpandingPanel_ContractionControlMustBeSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control &apos;{0}&apos; does not have the required CommandName property..
        /// </summary>
        internal static string ExpandingPanel_ControlMissingCommandNameProperty {
            get {
                return ResourceManager.GetString("ExpandingPanel_ControlMissingCommandNameProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExpansionControl must be set..
        /// </summary>
        internal static string ExpandingPanel_ExpansionControlMustBeSet {
            get {
                return ResourceManager.GetString("ExpandingPanel_ExpansionControlMustBeSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ControlState is invalid..
        /// </summary>
        internal static string InvalidControlState {
            get {
                return ResourceManager.GetString("InvalidControlState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ViewState Is Invalid.
        /// </summary>
        internal static string InvalidViewState {
            get {
                return ResourceManager.GetString("InvalidViewState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Over Client Count.
        /// </summary>
        internal static string License_OverClientCount {
            get {
                return ResourceManager.GetString("License_OverClientCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ChildList must be set..
        /// </summary>
        internal static string ListLink_ChildListSet {
            get {
                return ResourceManager.GetString("ListLink_ChildListSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ListControls must have a DataSet as their datasource.
        /// </summary>
        internal static string ListLink_DataSetOnly {
            get {
                return ResourceManager.GetString("ListLink_DataSetOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A ListControl named &apos;{0}&apos; cannot be found..
        /// </summary>
        internal static string ListLink_ListCannotBeFound {
            get {
                return ResourceManager.GetString("ListLink_ListCannotBeFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The DataRelation could not be found in the DataSource.
        /// </summary>
        internal static string ListLink_NoDataRelation {
            get {
                return ResourceManager.GetString("ListLink_NoDataRelation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ParentList must be set..
        /// </summary>
        internal static string ListLink_ParentListSet {
            get {
                return ResourceManager.GetString("ListLink_ParentListSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ListControls must have the same DataSource.
        /// </summary>
        internal static string ListLink_SameDataSource {
            get {
                return ResourceManager.GetString("ListLink_SameDataSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string MultiFileUpload_Add {
            get {
                return ResourceManager.GetString("MultiFileUpload_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MaxFiles must be set to a value great than 1.
        /// </summary>
        internal static string MultiFileUpload_MaxFilesGreaterThanOne {
            get {
                return ResourceManager.GetString("MultiFileUpload_MaxFilesGreaterThanOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        internal static string MultiFileUpload_Remove {
            get {
                return ResourceManager.GetString("MultiFileUpload_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --- Uploaded Files ---.
        /// </summary>
        internal static string MultiFileUpload_UploadedFilesHeader {
            get {
                return ResourceManager.GetString("MultiFileUpload_UploadedFilesHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value must be a MultiViewButtonPlacement member..
        /// </summary>
        internal static string MultiViewBar_ButtonPlacement_Invalid {
            get {
                return ResourceManager.GetString("MultiViewBar_ButtonPlacement_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MultiViewBar can only contain MultiViewItem controls. You tried add a child of type &apos;{0}&apos;..
        /// </summary>
        internal static string MultiViewBarControlCollection_MultiViewItems_Only {
            get {
                return ResourceManager.GetString("MultiViewBarControlCollection_MultiViewItems_Only", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add MultiViewItem controls by editing the Items collection..
        /// </summary>
        internal static string MultiViewBarDesigner_Add_Items {
            get {
                return ResourceManager.GetString("MultiViewBarDesigner_Add_Items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right click to edit the ContentTemplate for item &apos;{0}&apos;..
        /// </summary>
        internal static string MultiViewBarDesigner_Edit_Item_Template {
            get {
                return ResourceManager.GetString("MultiViewBarDesigner_Edit_Item_Template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MultiViewBarDesigner can only be used on controls of type MultiViewBar..
        /// </summary>
        internal static string MultiViewBarDesigner_Only_MultiViewBar {
            get {
                return ResourceManager.GetString("MultiViewBarDesigner_Only_MultiViewBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content Template.
        /// </summary>
        internal static string MultiViewBarDesigner_Template_Edit_Frame_Text {
            get {
                return ResourceManager.GetString("MultiViewBarDesigner_Template_Edit_Frame_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit ContentTemplate for item &apos;{0}&apos;.
        /// </summary>
        internal static string MultiViewBarDesigner_Template_Edit_Verb_Text {
            get {
                return ResourceManager.GetString("MultiViewBarDesigner_Template_Edit_Verb_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The String cannot be empty..
        /// </summary>
        internal static string Polling_StringCannotBeEmpty {
            get {
                return ResourceManager.GetString("Polling_StringCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not create Access database file at path &apos;(0}&apos;. Make sure the asp.net user has read/write permissions to this folder..
        /// </summary>
        internal static string PollingAccessProvider_CantCreateFile {
            get {
                return ResourceManager.GetString("PollingAccessProvider_CantCreateFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not locate the Access database resource to copy to the data folder. Copy the file manually..
        /// </summary>
        internal static string PollingAccessProvider_MissingAccessDatabaseResource {
            get {
                return ResourceManager.GetString("PollingAccessProvider_MissingAccessDatabaseResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string PollManager_CancelText {
            get {
                return ResourceManager.GetString("PollManager_CancelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Poll.
        /// </summary>
        internal static string PollManager_Default_AddNewPollButtonText {
            get {
                return ResourceManager.GetString("PollManager_Default_AddNewPollButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string PollManager_Default_AddOptionButtonText {
            get {
                return ResourceManager.GetString("PollManager_Default_AddOptionButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Option.
        /// </summary>
        internal static string PollManager_Default_AddOptionTitleText {
            get {
                return ResourceManager.GetString("PollManager_Default_AddOptionTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply Filter.
        /// </summary>
        internal static string PollManager_Default_ApplyFilterButtonText {
            get {
                return ResourceManager.GetString("PollManager_Default_ApplyFilterButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string PollManager_Default_CancelNewPollButtonText {
            get {
                return ResourceManager.GetString("PollManager_Default_CancelNewPollButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Votes.
        /// </summary>
        internal static string PollManager_Default_ClearPollVotesButtonText {
            get {
                return ResourceManager.GetString("PollManager_Default_ClearPollVotesButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this record?.
        /// </summary>
        internal static string PollManager_Default_DeleteConfirmationMessage {
            get {
                return ResourceManager.GetString("PollManager_Default_DeleteConfirmationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string PollManager_Default_DeletePollButtonText {
            get {
                return ResourceManager.GetString("PollManager_Default_DeletePollButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no visible polls..
        /// </summary>
        internal static string PollManager_Default_EmptyPollsLabelText {
            get {
                return ResourceManager.GetString("PollManager_Default_EmptyPollsLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active Dates.
        /// </summary>
        internal static string PollManager_Default_FilterActiveDatesLabelText {
            get {
                return ResourceManager.GetString("PollManager_Default_FilterActiveDatesLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        internal static string PollManager_Default_FilterCategoryLabelText {
            get {
                return ResourceManager.GetString("PollManager_Default_FilterCategoryLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poll Text.
        /// </summary>
        internal static string PollManager_Default_FilterPollTextLabelText {
            get {
                return ResourceManager.GetString("PollManager_Default_FilterPollTextLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        internal static string PollManager_Default_FilterTitleText {
            get {
                return ResourceManager.GetString("PollManager_Default_FilterTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Poll....
        /// </summary>
        internal static string PollManager_Default_NewPollButtonText {
            get {
                return ResourceManager.GetString("PollManager_Default_NewPollButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Poll.
        /// </summary>
        internal static string PollManager_Default_NewPollTitleText {
            get {
                return ResourceManager.GetString("PollManager_Default_NewPollTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Order.
        /// </summary>
        internal static string PollManager_Default_OptionDisplayOrderLabelText {
            get {
                return ResourceManager.GetString("PollManager_Default_OptionDisplayOrderLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        internal static string PollManager_Default_OptionEditorTitleText {
            get {
                return ResourceManager.GetString("PollManager_Default_OptionEditorTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        internal static string PollManager_Default_OptionTextLabelText {
            get {
                return ResourceManager.GetString("PollManager_Default_OptionTextLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow Write-Ins.
        /// </summary>
        internal static string PollManager_Default_PollAllowWriteInsLabelText {
            get {
                return ResourceManager.GetString("PollManager_Default_PollAllowWriteInsLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        internal static string PollManager_Default_PollCategoryLabelText {
            get {
                return ResourceManager.GetString("PollManager_Default_PollCategoryLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poll.
        /// </summary>
        internal static string PollManager_Default_PollEditorTitleText {
            get {
                return ResourceManager.GetString("PollManager_Default_PollEditorTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled.
        /// </summary>
        internal static string PollManager_Default_PollEnabledLabelText {
            get {
                return ResourceManager.GetString("PollManager_Default_PollEnabledLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        internal static string PollManager_Default_PollIdLabelText {
            get {
                return ResourceManager.GetString("PollManager_Default_PollIdLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date.
        /// </summary>
        internal static string PollManager_Default_PollStartDateLabelText {
            get {
                return ResourceManager.GetString("PollManager_Default_PollStartDateLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        internal static string PollManager_Default_PollTextLabelText {
            get {
                return ResourceManager.GetString("PollManager_Default_PollTextLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vote Mode.
        /// </summary>
        internal static string PollManager_Default_PollVoteModeLabelText {
            get {
                return ResourceManager.GetString("PollManager_Default_PollVoteModeLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        internal static string PollManager_Default_UpdatePollButtonText {
            get {
                return ResourceManager.GetString("PollManager_Default_UpdatePollButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string PollManager_DeleteText {
            get {
                return ResourceManager.GetString("PollManager_DeleteText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string PollManager_EditText {
            get {
                return ResourceManager.GetString("PollManager_EditText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user &apos;{0}&apos; attempted to change poll data without being a member of the proper role..
        /// </summary>
        internal static string PollManager_UnauthorizedUser {
            get {
                return ResourceManager.GetString("PollManager_UnauthorizedUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        internal static string PollManager_UpdateText {
            get {
                return ResourceManager.GetString("PollManager_UpdateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be a whole number.
        /// </summary>
        internal static string PollManager_Validation_DisplayOrderMustBeNumber {
            get {
                return ResourceManager.GetString("PollManager_Validation_DisplayOrderMustBeNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *.
        /// </summary>
        internal static string PollManager_Validation_OptionTextRequired {
            get {
                return ResourceManager.GetString("PollManager_Validation_OptionTextRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The given custom poll value is invalid..
        /// </summary>
        internal static string PollView_CustomPollID_Invalid {
            get {
                return ResourceManager.GetString("PollView_CustomPollID_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no poll to show..
        /// </summary>
        internal static string PollView_NoPollText {
            get {
                return ResourceManager.GetString("PollView_NoPollText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Results.
        /// </summary>
        internal static string PollView_ShowResultsText {
            get {
                return ResourceManager.GetString("PollView_ShowResultsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show write-ins.
        /// </summary>
        internal static string PollView_ShowWriteInButtonText {
            get {
                return ResourceManager.GetString("PollView_ShowWriteInButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vote.
        /// </summary>
        internal static string PollView_VoteText {
            get {
                return ResourceManager.GetString("PollView_VoteText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write-In Votes.
        /// </summary>
        internal static string PollView_WriteInHeaderText {
            get {
                return ResourceManager.GetString("PollView_WriteInHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to functionNames must contain at least one string..
        /// </summary>
        internal static string QueryCall_FunctionNamesEmpty {
            get {
                return ResourceManager.GetString("QueryCall_FunctionNamesEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to functionNames cannot be Null..
        /// </summary>
        internal static string QueryCall_FunctionNamesNull {
            get {
                return ResourceManager.GetString("QueryCall_FunctionNamesNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Down.
        /// </summary>
        internal static string Standard_Down {
            get {
                return ResourceManager.GetString("Standard_Down", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Up.
        /// </summary>
        internal static string Standard_Up {
            get {
                return ResourceManager.GetString("Standard_Up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unbound.
        /// </summary>
        internal static string UnDataBound {
            get {
                return ResourceManager.GetString("UnDataBound", resourceCulture);
            }
        }
    }
}
