// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code. Version 3.4.0.38967
//    <NameSpace>MailsendWPF</NameSpace><Collection>ObservableCollection</Collection><codeType>CSharp</codeType><EnableDataBinding>True</EnableDataBinding><EnableLazyLoading>True</EnableLazyLoading><TrackingChangesEnable>False</TrackingChangesEnable><GenTrackingClasses>False</GenTrackingClasses><HidePrivateFieldInIDE>False</HidePrivateFieldInIDE><EnableSummaryComment>False</EnableSummaryComment><VirtualProp>False</VirtualProp><IncludeSerializeMethod>True</IncludeSerializeMethod><UseBaseClass>True</UseBaseClass><GenBaseClass>True</GenBaseClass><GenerateCloneMethod>True</GenerateCloneMethod><GenerateDataContracts>False</GenerateDataContracts><CodeBaseTag>Net40</CodeBaseTag><SerializeMethodName>Serialize</SerializeMethodName><DeserializeMethodName>Deserialize</DeserializeMethodName><SaveToFileMethodName>SaveToFile</SaveToFileMethodName><LoadFromFileMethodName>LoadFromFile</LoadFromFileMethodName><GenerateXMLAttributes>True</GenerateXMLAttributes><EnableEncoding>True</EnableEncoding><AutomaticProperties>False</AutomaticProperties><GenerateShouldSerialize>True</GenerateShouldSerialize><DisableDebug>False</DisableDebug><PropNameSpecified>Default</PropNameSpecified><Encoder>UTF8</Encoder><CustomUsings></CustomUsings><ExcludeIncludedTypes>False</ExcludeIncludedTypes><EnableInitializeFields>True</EnableInitializeFields>
//  </auto-generated>
// ------------------------------------------------------------------------------
namespace MailsendWPF
{
    using System;
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System.Collections;
    using System.Xml.Schema;
    using System.ComponentModel;
    using System.IO;
    using System.Text;
    using System.Xml;
    using System.Collections.ObjectModel;


    #region Base entity class
    public partial class EntityBase<T> : System.ComponentModel.INotifyPropertyChanged
    {

        private static System.Xml.Serialization.XmlSerializer serializer;

        private static System.Xml.Serialization.XmlSerializer Serializer
        {
            get
            {
                if ((serializer == null))
                {
                    serializer = new System.Xml.Serialization.XmlSerializer(typeof(T));
                }
                return serializer;
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        public virtual void OnPropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler handler = this.PropertyChanged;
            if ((handler != null))
            {
                handler(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }

        #region Serialize/Deserialize
        /// <summary>
        /// Serializes current EntityBase object into an XML document
        /// </summary>
        /// <returns>string XML value</returns>
        public virtual string Serialize(System.Text.Encoding encoding)
        {
            System.IO.StreamReader streamReader = null;
            System.IO.MemoryStream memoryStream = null;
            try
            {
                memoryStream = new System.IO.MemoryStream();
                System.Xml.XmlWriterSettings xmlWriterSettings = new System.Xml.XmlWriterSettings();
                xmlWriterSettings.Encoding = encoding;
                System.Xml.XmlWriter xmlWriter = XmlWriter.Create(memoryStream, xmlWriterSettings);
                Serializer.Serialize(xmlWriter, this);
                memoryStream.Seek(0, System.IO.SeekOrigin.Begin);
                streamReader = new System.IO.StreamReader(memoryStream);
                return streamReader.ReadToEnd();
            }
            finally
            {
                if ((streamReader != null))
                {
                    streamReader.Dispose();
                }
                if ((memoryStream != null))
                {
                    memoryStream.Dispose();
                }
            }
        }

        public virtual string Serialize()
        {
            return Serialize(Encoding.UTF8);
        }

        /// <summary>
        /// Deserializes workflow markup into an EntityBase object
        /// </summary>
        /// <param name="xml">string workflow markup to deserialize</param>
        /// <param name="obj">Output EntityBase object</param>
        /// <param name="exception">output Exception value if deserialize failed</param>
        /// <returns>true if this XmlSerializer can deserialize the object; otherwise, false</returns>
        public static bool Deserialize(string xml, out T obj, out System.Exception exception)
        {
            exception = null;
            obj = default(T);
            try
            {
                obj = Deserialize(xml);
                return true;
            }
            catch (System.Exception ex)
            {
                exception = ex;
                return false;
            }
        }

        public static bool Deserialize(string xml, out T obj)
        {
            System.Exception exception = null;
            return Deserialize(xml, out obj, out exception);
        }

        public static T Deserialize(string xml)
        {
            System.IO.StringReader stringReader = null;
            try
            {
                stringReader = new System.IO.StringReader(xml);
                return ((T)(Serializer.Deserialize(System.Xml.XmlReader.Create(stringReader))));
            }
            finally
            {
                if ((stringReader != null))
                {
                    stringReader.Dispose();
                }
            }
        }

        /// <summary>
        /// Serializes current EntityBase object into file
        /// </summary>
        /// <param name="fileName">full path of outupt xml file</param>
        /// <param name="exception">output Exception value if failed</param>
        /// <returns>true if can serialize and save into file; otherwise, false</returns>
        public virtual bool SaveToFile(string fileName, System.Text.Encoding encoding, out System.Exception exception)
        {
            exception = null;
            try
            {
                SaveToFile(fileName, encoding);
                return true;
            }
            catch (System.Exception e)
            {
                exception = e;
                return false;
            }
        }

        public virtual bool SaveToFile(string fileName, out System.Exception exception)
        {
            return SaveToFile(fileName, Encoding.UTF8, out exception);
        }

        public virtual void SaveToFile(string fileName)
        {
            SaveToFile(fileName, Encoding.UTF8);
        }

        public virtual void SaveToFile(string fileName, System.Text.Encoding encoding)
        {
            System.IO.StreamWriter streamWriter = null;
            try
            {
                string xmlString = Serialize(encoding);
                streamWriter = new System.IO.StreamWriter(fileName, false, Encoding.UTF8);
                streamWriter.WriteLine(xmlString);
                streamWriter.Close();
            }
            finally
            {
                if ((streamWriter != null))
                {
                    streamWriter.Dispose();
                }
            }
        }

        /// <summary>
        /// Deserializes xml markup from file into an EntityBase object
        /// </summary>
        /// <param name="fileName">string xml file to load and deserialize</param>
        /// <param name="obj">Output EntityBase object</param>
        /// <param name="exception">output Exception value if deserialize failed</param>
        /// <returns>true if this XmlSerializer can deserialize the object; otherwise, false</returns>
        public static bool LoadFromFile(string fileName, System.Text.Encoding encoding, out T obj, out System.Exception exception)
        {
            exception = null;
            obj = default(T);
            try
            {
                obj = LoadFromFile(fileName, encoding);
                return true;
            }
            catch (System.Exception ex)
            {
                exception = ex;
                return false;
            }
        }

        public static bool LoadFromFile(string fileName, out T obj, out System.Exception exception)
        {
            return LoadFromFile(fileName, Encoding.UTF8, out obj, out exception);
        }

        public static bool LoadFromFile(string fileName, out T obj)
        {
            System.Exception exception = null;
            return LoadFromFile(fileName, out obj, out exception);
        }

        public static T LoadFromFile(string fileName)
        {
            return LoadFromFile(fileName, Encoding.UTF8);
        }

        public static T LoadFromFile(string fileName, System.Text.Encoding encoding)
        {
            System.IO.FileStream file = null;
            System.IO.StreamReader sr = null;
            try
            {
                file = new System.IO.FileStream(fileName, FileMode.Open, FileAccess.Read);
                sr = new System.IO.StreamReader(file, encoding);
                string xmlString = sr.ReadToEnd();
                sr.Close();
                file.Close();
                return Deserialize(xmlString);
            }
            finally
            {
                if ((file != null))
                {
                    file.Dispose();
                }
                if ((sr != null))
                {
                    sr.Dispose();
                }
            }
        }
        #endregion

        #region Clone method
        /// <summary>
        /// Create a clone of this T object
        /// </summary>
        public virtual T Clone()
        {
            return ((T)(this.MemberwiseClone()));
        }
        #endregion
    }
    #endregion

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://tempuri.org/MailConfig.xsd")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://tempuri.org/MailConfig.xsd", IsNullable = false)]
    public partial class ServerSchema : EntityBase<ServerSchema>
    {

        private string mailToField;

        private string mailFromField;

        private string smartHostField;

        private string hostField;

        private string displayNameField;

        private string portField;

        private string userField;

        private string pwdField;

        private ObservableCollection<string> mailDirField;

        private string filterField;

        private ulong roundsField;

        private string connectionsField;

        private bool endlessSendingField;

        private bool recursiveField;

        private bool anonymousAuthField;

        private bool basicAuthField;

        private ObservableCollection<ServerSchemaHeader> headerField;

        private ServerSchemaSubject subjectField;

        private bool parsedField;

        private string waitBetweenMailsmsField;

        private bool sendOriginalField;

        private bool newMessageIDField;

        private bool deleteMessageIDField;

        private bool originalMessageIDField;

        private bool fallBackField;

        private long cacheMailsUntilInByteField;

        private bool exPandServerField;

        private bool mailSendWindowExpandField;

        private ulong mailsCountField;

        private bool addRecipientToMailField;

        private bool addSenderToMailField;

        private string codePageField;

        private bool codePageEnabledField;

        private bool visibleField;

        private string externalProgramField;

        private ObservableCollection<string> kommentarField;

        private string recipientGroupField;

        private string recipientGroupStartField;

        private string recipientGroupEndField;

        private string recipientGroupDomainField;

        private bool cHKUseRecipientGroupField;

        private string senderGroupField;

        private string senderGroupStartField;

        private string senderGroupEndField;

        private string senderGroupDomainField;

        private bool cHKUseSenderGroupField;

        private bool addHeaderField;

        private bool loggingField;

        private string receiveBufferField;

        private string sendBufferField;

        private string receiveTimeoutField;

        private string sendTimeoutField;

        private bool ignoreAllErrorsField;

        private bool useTLSField;

        private bool useSSLSecuredPortField;

        private bool noSSLField;

        private string mailFilePathField;

        private string mailFolderPathField;

        private string testMailHeaderField;

        private string testMailBodyField;

        private bool keyManagerUseField;

        private bool keyManagerTestField;

        private bool getPrivateKeyRequestField;

        private bool getAllPrivateKeysForEmailRequestField;

        private bool getOrCreatePrivateKeyAdvancedRequestField;

        private bool getOrCreatePrivateKeyRequestField;

        private bool get509CertificateRequestField;

        private bool importX509CertificateRequestField;

        private string importFromTenantField;

        private bool getAllX509CertificatesForEmailRequestField;

        private bool getPrivateKeyFromEnvelopeRequestField;

        private bool getX509CertificateForVerificationBySignedDataRequestField;

        private bool makeCyclicCertsForAllTenantsSameField;

        private string privateKeyTypeField;

        private string publicKeyTypeField;

        private ObservableCollection<ServerSchemaTenants> tenantsField;

        public ServerSchema()
        {
            this.portField = "25";
            this.filterField = "*.eml";
            this.roundsField = ((ulong)(1m));
            this.connectionsField = "1";
            this.endlessSendingField = false;
            this.recursiveField = false;
            this.anonymousAuthField = true;
            this.basicAuthField = false;
            this.parsedField = false;
            this.waitBetweenMailsmsField = "0";
            this.sendOriginalField = true;
            this.newMessageIDField = false;
            this.deleteMessageIDField = true;
            this.originalMessageIDField = false;
            this.fallBackField = true;
            this.cacheMailsUntilInByteField = ((long)(0));
            this.exPandServerField = true;
            this.mailSendWindowExpandField = true;
            this.mailsCountField = ((ulong)(0m));
            this.addRecipientToMailField = false;
            this.addSenderToMailField = false;
            this.codePageField = "65001";
            this.codePageEnabledField = false;
            this.visibleField = false;
            this.recipientGroupField = "";
            this.recipientGroupStartField = "0";
            this.recipientGroupEndField = "0";
            this.cHKUseRecipientGroupField = false;
            this.senderGroupField = "";
            this.senderGroupStartField = "0";
            this.senderGroupEndField = "0";
            this.cHKUseSenderGroupField = false;
            this.addHeaderField = false;
            this.loggingField = false;
            this.receiveBufferField = "8192";
            this.sendBufferField = "8192";
            this.receiveTimeoutField = "90000";
            this.sendTimeoutField = "90000";
            this.ignoreAllErrorsField = false;
            this.useTLSField = false;
            this.useSSLSecuredPortField = false;
            this.noSSLField = true;
            this.mailFilePathField = "";
            this.mailFolderPathField = "";
            this.testMailHeaderField = "";
            this.testMailBodyField = "This is a MailSend Testmail";
            this.keyManagerUseField = false;
            this.keyManagerTestField = false;
            this.getPrivateKeyRequestField = false;
            this.getAllPrivateKeysForEmailRequestField = false;
            this.getOrCreatePrivateKeyAdvancedRequestField = false;
            this.getOrCreatePrivateKeyRequestField = false;
            this.get509CertificateRequestField = false;
            this.importX509CertificateRequestField = false;
            this.importFromTenantField = "";
            this.getAllX509CertificatesForEmailRequestField = false;
            this.getPrivateKeyFromEnvelopeRequestField = false;
            this.getX509CertificateForVerificationBySignedDataRequestField = false;
            this.makeCyclicCertsForAllTenantsSameField = true;
            this.privateKeyTypeField = "";
            this.publicKeyTypeField = "";
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public string MailTo
        {
            get
            {
                return this.mailToField;
            }
            set
            {
                if ((this.mailToField != null))
                {
                    if ((mailToField.Equals(value) != true))
                    {
                        this.mailToField = value;
                        this.OnPropertyChanged("MailTo");
                    }
                }
                else
                {
                    this.mailToField = value;
                    this.OnPropertyChanged("MailTo");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public string MailFrom
        {
            get
            {
                return this.mailFromField;
            }
            set
            {
                if ((this.mailFromField != null))
                {
                    if ((mailFromField.Equals(value) != true))
                    {
                        this.mailFromField = value;
                        this.OnPropertyChanged("MailFrom");
                    }
                }
                else
                {
                    this.mailFromField = value;
                    this.OnPropertyChanged("MailFrom");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public string SmartHost
        {
            get
            {
                return this.smartHostField;
            }
            set
            {
                if ((this.smartHostField != null))
                {
                    if ((smartHostField.Equals(value) != true))
                    {
                        this.smartHostField = value;
                        this.OnPropertyChanged("SmartHost");
                    }
                }
                else
                {
                    this.smartHostField = value;
                    this.OnPropertyChanged("SmartHost");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
        public string Host
        {
            get
            {
                return this.hostField;
            }
            set
            {
                if ((this.hostField != null))
                {
                    if ((hostField.Equals(value) != true))
                    {
                        this.hostField = value;
                        this.OnPropertyChanged("Host");
                    }
                }
                else
                {
                    this.hostField = value;
                    this.OnPropertyChanged("Host");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 4)]
        public string DisplayName
        {
            get
            {
                return this.displayNameField;
            }
            set
            {
                if ((this.displayNameField != null))
                {
                    if ((displayNameField.Equals(value) != true))
                    {
                        this.displayNameField = value;
                        this.OnPropertyChanged("DisplayName");
                    }
                }
                else
                {
                    this.displayNameField = value;
                    this.OnPropertyChanged("DisplayName");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(DataType = "integer", Order = 5)]
        public string Port
        {
            get
            {
                return this.portField;
            }
            set
            {
                if ((this.portField != null))
                {
                    if ((portField.Equals(value) != true))
                    {
                        this.portField = value;
                        this.OnPropertyChanged("Port");
                    }
                }
                else
                {
                    this.portField = value;
                    this.OnPropertyChanged("Port");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 6)]
        public string User
        {
            get
            {
                return this.userField;
            }
            set
            {
                if ((this.userField != null))
                {
                    if ((userField.Equals(value) != true))
                    {
                        this.userField = value;
                        this.OnPropertyChanged("User");
                    }
                }
                else
                {
                    this.userField = value;
                    this.OnPropertyChanged("User");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 7)]
        public string Pwd
        {
            get
            {
                return this.pwdField;
            }
            set
            {
                if ((this.pwdField != null))
                {
                    if ((pwdField.Equals(value) != true))
                    {
                        this.pwdField = value;
                        this.OnPropertyChanged("Pwd");
                    }
                }
                else
                {
                    this.pwdField = value;
                    this.OnPropertyChanged("Pwd");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute("MailDir", Order = 8)]
        public ObservableCollection<string> MailDir
        {
            get
            {
                if ((this.mailDirField == null))
                {
                    this.mailDirField = new ObservableCollection<string>();
                }
                return this.mailDirField;
            }
            set
            {
                if ((this.mailDirField != null))
                {
                    if ((mailDirField.Equals(value) != true))
                    {
                        this.mailDirField = value;
                        this.OnPropertyChanged("MailDir");
                    }
                }
                else
                {
                    this.mailDirField = value;
                    this.OnPropertyChanged("MailDir");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 9)]
        public string Filter
        {
            get
            {
                return this.filterField;
            }
            set
            {
                if ((this.filterField != null))
                {
                    if ((filterField.Equals(value) != true))
                    {
                        this.filterField = value;
                        this.OnPropertyChanged("Filter");
                    }
                }
                else
                {
                    this.filterField = value;
                    this.OnPropertyChanged("Filter");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 10)]
        public ulong Rounds
        {
            get
            {
                return this.roundsField;
            }
            set
            {
                if ((this.roundsField != null))
                {
                    if ((roundsField.Equals(value) != true))
                    {
                        this.roundsField = value;
                        this.OnPropertyChanged("Rounds");
                    }
                }
                else
                {
                    this.roundsField = value;
                    this.OnPropertyChanged("Rounds");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(DataType = "integer", Order = 11)]
        public string Connections
        {
            get
            {
                return this.connectionsField;
            }
            set
            {
                if ((this.connectionsField != null))
                {
                    if ((connectionsField.Equals(value) != true))
                    {
                        this.connectionsField = value;
                        this.OnPropertyChanged("Connections");
                    }
                }
                else
                {
                    this.connectionsField = value;
                    this.OnPropertyChanged("Connections");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 12)]
        public bool EndlessSending
        {
            get
            {
                return this.endlessSendingField;
            }
            set
            {
                if ((endlessSendingField.Equals(value) != true))
                {
                    this.endlessSendingField = value;
                    this.OnPropertyChanged("EndlessSending");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 13)]
        public bool Recursive
        {
            get
            {
                return this.recursiveField;
            }
            set
            {
                if ((recursiveField.Equals(value) != true))
                {
                    this.recursiveField = value;
                    this.OnPropertyChanged("Recursive");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 14)]
        public bool AnonymousAuth
        {
            get
            {
                return this.anonymousAuthField;
            }
            set
            {
                if ((anonymousAuthField.Equals(value) != true))
                {
                    this.anonymousAuthField = value;
                    this.OnPropertyChanged("AnonymousAuth");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 15)]
        public bool BasicAuth
        {
            get
            {
                return this.basicAuthField;
            }
            set
            {
                if ((basicAuthField.Equals(value) != true))
                {
                    this.basicAuthField = value;
                    this.OnPropertyChanged("BasicAuth");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute("Header", Order = 16)]
        public ObservableCollection<ServerSchemaHeader> Header
        {
            get
            {
                if ((this.headerField == null))
                {
                    this.headerField = new ObservableCollection<ServerSchemaHeader>();
                }
                return this.headerField;
            }
            set
            {
                if ((this.headerField != null))
                {
                    if ((headerField.Equals(value) != true))
                    {
                        this.headerField = value;
                        this.OnPropertyChanged("Header");
                    }
                }
                else
                {
                    this.headerField = value;
                    this.OnPropertyChanged("Header");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 17)]
        public ServerSchemaSubject Subject
        {
            get
            {
                if ((this.subjectField == null))
                {
                    this.subjectField = new ServerSchemaSubject();
                }
                return this.subjectField;
            }
            set
            {
                if ((this.subjectField != null))
                {
                    if ((subjectField.Equals(value) != true))
                    {
                        this.subjectField = value;
                        this.OnPropertyChanged("Subject");
                    }
                }
                else
                {
                    this.subjectField = value;
                    this.OnPropertyChanged("Subject");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 18)]
        public bool Parsed
        {
            get
            {
                return this.parsedField;
            }
            set
            {
                if ((parsedField.Equals(value) != true))
                {
                    this.parsedField = value;
                    this.OnPropertyChanged("Parsed");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(DataType = "integer", Order = 19)]
        public string WaitBetweenMailsms
        {
            get
            {
                return this.waitBetweenMailsmsField;
            }
            set
            {
                if ((this.waitBetweenMailsmsField != null))
                {
                    if ((waitBetweenMailsmsField.Equals(value) != true))
                    {
                        this.waitBetweenMailsmsField = value;
                        this.OnPropertyChanged("WaitBetweenMailsms");
                    }
                }
                else
                {
                    this.waitBetweenMailsmsField = value;
                    this.OnPropertyChanged("WaitBetweenMailsms");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 20)]
        public bool SendOriginal
        {
            get
            {
                return this.sendOriginalField;
            }
            set
            {
                if ((sendOriginalField.Equals(value) != true))
                {
                    this.sendOriginalField = value;
                    this.OnPropertyChanged("SendOriginal");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 21)]
        public bool NewMessageID
        {
            get
            {
                return this.newMessageIDField;
            }
            set
            {
                if ((newMessageIDField.Equals(value) != true))
                {
                    this.newMessageIDField = value;
                    this.OnPropertyChanged("NewMessageID");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 22)]
        public bool DeleteMessageID
        {
            get
            {
                return this.deleteMessageIDField;
            }
            set
            {
                if ((deleteMessageIDField.Equals(value) != true))
                {
                    this.deleteMessageIDField = value;
                    this.OnPropertyChanged("DeleteMessageID");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 23)]
        public bool OriginalMessageID
        {
            get
            {
                return this.originalMessageIDField;
            }
            set
            {
                if ((originalMessageIDField.Equals(value) != true))
                {
                    this.originalMessageIDField = value;
                    this.OnPropertyChanged("OriginalMessageID");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 24)]
        public bool FallBack
        {
            get
            {
                return this.fallBackField;
            }
            set
            {
                if ((fallBackField.Equals(value) != true))
                {
                    this.fallBackField = value;
                    this.OnPropertyChanged("FallBack");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 25)]
        public long CacheMailsUntilInByte
        {
            get
            {
                return this.cacheMailsUntilInByteField;
            }
            set
            {
                if ((cacheMailsUntilInByteField.Equals(value) != true))
                {
                    this.cacheMailsUntilInByteField = value;
                    this.OnPropertyChanged("CacheMailsUntilInByte");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 26)]
        public bool ExPandServer
        {
            get
            {
                return this.exPandServerField;
            }
            set
            {
                if ((exPandServerField.Equals(value) != true))
                {
                    this.exPandServerField = value;
                    this.OnPropertyChanged("ExPandServer");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 27)]
        public bool MailSendWindowExpand
        {
            get
            {
                return this.mailSendWindowExpandField;
            }
            set
            {
                if ((mailSendWindowExpandField.Equals(value) != true))
                {
                    this.mailSendWindowExpandField = value;
                    this.OnPropertyChanged("MailSendWindowExpand");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 28)]
        public ulong MailsCount
        {
            get
            {
                return this.mailsCountField;
            }
            set
            {
                if ((this.mailsCountField != null))
                {
                    if ((mailsCountField.Equals(value) != true))
                    {
                        this.mailsCountField = value;
                        this.OnPropertyChanged("MailsCount");
                    }
                }
                else
                {
                    this.mailsCountField = value;
                    this.OnPropertyChanged("MailsCount");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 29)]
        public bool AddRecipientToMail
        {
            get
            {
                return this.addRecipientToMailField;
            }
            set
            {
                if ((addRecipientToMailField.Equals(value) != true))
                {
                    this.addRecipientToMailField = value;
                    this.OnPropertyChanged("AddRecipientToMail");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 30)]
        public bool AddSenderToMail
        {
            get
            {
                return this.addSenderToMailField;
            }
            set
            {
                if ((addSenderToMailField.Equals(value) != true))
                {
                    this.addSenderToMailField = value;
                    this.OnPropertyChanged("AddSenderToMail");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(DataType = "integer", Order = 31)]
        public string CodePage
        {
            get
            {
                return this.codePageField;
            }
            set
            {
                if ((this.codePageField != null))
                {
                    if ((codePageField.Equals(value) != true))
                    {
                        this.codePageField = value;
                        this.OnPropertyChanged("CodePage");
                    }
                }
                else
                {
                    this.codePageField = value;
                    this.OnPropertyChanged("CodePage");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 32)]
        public bool CodePageEnabled
        {
            get
            {
                return this.codePageEnabledField;
            }
            set
            {
                if ((codePageEnabledField.Equals(value) != true))
                {
                    this.codePageEnabledField = value;
                    this.OnPropertyChanged("CodePageEnabled");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 33)]
        public bool Visible
        {
            get
            {
                return this.visibleField;
            }
            set
            {
                if ((visibleField.Equals(value) != true))
                {
                    this.visibleField = value;
                    this.OnPropertyChanged("Visible");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 34)]
        public string ExternalProgram
        {
            get
            {
                return this.externalProgramField;
            }
            set
            {
                if ((this.externalProgramField != null))
                {
                    if ((externalProgramField.Equals(value) != true))
                    {
                        this.externalProgramField = value;
                        this.OnPropertyChanged("ExternalProgram");
                    }
                }
                else
                {
                    this.externalProgramField = value;
                    this.OnPropertyChanged("ExternalProgram");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute("Kommentar", Order = 35)]
        public ObservableCollection<string> Kommentar
        {
            get
            {
                if ((this.kommentarField == null))
                {
                    this.kommentarField = new ObservableCollection<string>();
                }
                return this.kommentarField;
            }
            set
            {
                if ((this.kommentarField != null))
                {
                    if ((kommentarField.Equals(value) != true))
                    {
                        this.kommentarField = value;
                        this.OnPropertyChanged("Kommentar");
                    }
                }
                else
                {
                    this.kommentarField = value;
                    this.OnPropertyChanged("Kommentar");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 36)]
        public string RecipientGroup
        {
            get
            {
                return this.recipientGroupField;
            }
            set
            {
                if ((this.recipientGroupField != null))
                {
                    if ((recipientGroupField.Equals(value) != true))
                    {
                        this.recipientGroupField = value;
                        this.OnPropertyChanged("RecipientGroup");
                    }
                }
                else
                {
                    this.recipientGroupField = value;
                    this.OnPropertyChanged("RecipientGroup");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(DataType = "integer", Order = 37)]
        public string RecipientGroupStart
        {
            get
            {
                return this.recipientGroupStartField;
            }
            set
            {
                if ((this.recipientGroupStartField != null))
                {
                    if ((recipientGroupStartField.Equals(value) != true))
                    {
                        this.recipientGroupStartField = value;
                        this.OnPropertyChanged("RecipientGroupStart");
                    }
                }
                else
                {
                    this.recipientGroupStartField = value;
                    this.OnPropertyChanged("RecipientGroupStart");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(DataType = "integer", Order = 38)]
        public string RecipientGroupEnd
        {
            get
            {
                return this.recipientGroupEndField;
            }
            set
            {
                if ((this.recipientGroupEndField != null))
                {
                    if ((recipientGroupEndField.Equals(value) != true))
                    {
                        this.recipientGroupEndField = value;
                        this.OnPropertyChanged("RecipientGroupEnd");
                    }
                }
                else
                {
                    this.recipientGroupEndField = value;
                    this.OnPropertyChanged("RecipientGroupEnd");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 39)]
        public string RecipientGroupDomain
        {
            get
            {
                return this.recipientGroupDomainField;
            }
            set
            {
                if ((this.recipientGroupDomainField != null))
                {
                    if ((recipientGroupDomainField.Equals(value) != true))
                    {
                        this.recipientGroupDomainField = value;
                        this.OnPropertyChanged("RecipientGroupDomain");
                    }
                }
                else
                {
                    this.recipientGroupDomainField = value;
                    this.OnPropertyChanged("RecipientGroupDomain");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 40)]
        public bool CHKUseRecipientGroup
        {
            get
            {
                return this.cHKUseRecipientGroupField;
            }
            set
            {
                if ((cHKUseRecipientGroupField.Equals(value) != true))
                {
                    this.cHKUseRecipientGroupField = value;
                    this.OnPropertyChanged("CHKUseRecipientGroup");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 41)]
        public string SenderGroup
        {
            get
            {
                return this.senderGroupField;
            }
            set
            {
                if ((this.senderGroupField != null))
                {
                    if ((senderGroupField.Equals(value) != true))
                    {
                        this.senderGroupField = value;
                        this.OnPropertyChanged("SenderGroup");
                    }
                }
                else
                {
                    this.senderGroupField = value;
                    this.OnPropertyChanged("SenderGroup");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(DataType = "integer", Order = 42)]
        public string SenderGroupStart
        {
            get
            {
                return this.senderGroupStartField;
            }
            set
            {
                if ((this.senderGroupStartField != null))
                {
                    if ((senderGroupStartField.Equals(value) != true))
                    {
                        this.senderGroupStartField = value;
                        this.OnPropertyChanged("SenderGroupStart");
                    }
                }
                else
                {
                    this.senderGroupStartField = value;
                    this.OnPropertyChanged("SenderGroupStart");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(DataType = "integer", Order = 43)]
        public string SenderGroupEnd
        {
            get
            {
                return this.senderGroupEndField;
            }
            set
            {
                if ((this.senderGroupEndField != null))
                {
                    if ((senderGroupEndField.Equals(value) != true))
                    {
                        this.senderGroupEndField = value;
                        this.OnPropertyChanged("SenderGroupEnd");
                    }
                }
                else
                {
                    this.senderGroupEndField = value;
                    this.OnPropertyChanged("SenderGroupEnd");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 44)]
        public string SenderGroupDomain
        {
            get
            {
                return this.senderGroupDomainField;
            }
            set
            {
                if ((this.senderGroupDomainField != null))
                {
                    if ((senderGroupDomainField.Equals(value) != true))
                    {
                        this.senderGroupDomainField = value;
                        this.OnPropertyChanged("SenderGroupDomain");
                    }
                }
                else
                {
                    this.senderGroupDomainField = value;
                    this.OnPropertyChanged("SenderGroupDomain");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 45)]
        public bool CHKUseSenderGroup
        {
            get
            {
                return this.cHKUseSenderGroupField;
            }
            set
            {
                if ((cHKUseSenderGroupField.Equals(value) != true))
                {
                    this.cHKUseSenderGroupField = value;
                    this.OnPropertyChanged("CHKUseSenderGroup");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 46)]
        public bool AddHeader
        {
            get
            {
                return this.addHeaderField;
            }
            set
            {
                if ((addHeaderField.Equals(value) != true))
                {
                    this.addHeaderField = value;
                    this.OnPropertyChanged("AddHeader");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 47)]
        public bool Logging
        {
            get
            {
                return this.loggingField;
            }
            set
            {
                if ((loggingField.Equals(value) != true))
                {
                    this.loggingField = value;
                    this.OnPropertyChanged("Logging");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(DataType = "integer", Order = 48)]
        public string ReceiveBuffer
        {
            get
            {
                return this.receiveBufferField;
            }
            set
            {
                if ((this.receiveBufferField != null))
                {
                    if ((receiveBufferField.Equals(value) != true))
                    {
                        this.receiveBufferField = value;
                        this.OnPropertyChanged("ReceiveBuffer");
                    }
                }
                else
                {
                    this.receiveBufferField = value;
                    this.OnPropertyChanged("ReceiveBuffer");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(DataType = "integer", Order = 49)]
        public string SendBuffer
        {
            get
            {
                return this.sendBufferField;
            }
            set
            {
                if ((this.sendBufferField != null))
                {
                    if ((sendBufferField.Equals(value) != true))
                    {
                        this.sendBufferField = value;
                        this.OnPropertyChanged("SendBuffer");
                    }
                }
                else
                {
                    this.sendBufferField = value;
                    this.OnPropertyChanged("SendBuffer");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(DataType = "integer", Order = 50)]
        public string ReceiveTimeout
        {
            get
            {
                return this.receiveTimeoutField;
            }
            set
            {
                if ((this.receiveTimeoutField != null))
                {
                    if ((receiveTimeoutField.Equals(value) != true))
                    {
                        this.receiveTimeoutField = value;
                        this.OnPropertyChanged("ReceiveTimeout");
                    }
                }
                else
                {
                    this.receiveTimeoutField = value;
                    this.OnPropertyChanged("ReceiveTimeout");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(DataType = "integer", Order = 51)]
        public string SendTimeout
        {
            get
            {
                return this.sendTimeoutField;
            }
            set
            {
                if ((this.sendTimeoutField != null))
                {
                    if ((sendTimeoutField.Equals(value) != true))
                    {
                        this.sendTimeoutField = value;
                        this.OnPropertyChanged("SendTimeout");
                    }
                }
                else
                {
                    this.sendTimeoutField = value;
                    this.OnPropertyChanged("SendTimeout");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 52)]
        public bool IgnoreAllErrors
        {
            get
            {
                return this.ignoreAllErrorsField;
            }
            set
            {
                if ((ignoreAllErrorsField.Equals(value) != true))
                {
                    this.ignoreAllErrorsField = value;
                    this.OnPropertyChanged("IgnoreAllErrors");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 53)]
        public bool UseTLS
        {
            get
            {
                return this.useTLSField;
            }
            set
            {
                if ((useTLSField.Equals(value) != true))
                {
                    this.useTLSField = value;
                    this.OnPropertyChanged("UseTLS");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 54)]
        public bool UseSSLSecuredPort
        {
            get
            {
                return this.useSSLSecuredPortField;
            }
            set
            {
                if ((useSSLSecuredPortField.Equals(value) != true))
                {
                    this.useSSLSecuredPortField = value;
                    this.OnPropertyChanged("UseSSLSecuredPort");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 55)]
        public bool NoSSL
        {
            get
            {
                return this.noSSLField;
            }
            set
            {
                if ((noSSLField.Equals(value) != true))
                {
                    this.noSSLField = value;
                    this.OnPropertyChanged("NoSSL");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 56)]
        public string MailFilePath
        {
            get
            {
                return this.mailFilePathField;
            }
            set
            {
                if ((this.mailFilePathField != null))
                {
                    if ((mailFilePathField.Equals(value) != true))
                    {
                        this.mailFilePathField = value;
                        this.OnPropertyChanged("MailFilePath");
                    }
                }
                else
                {
                    this.mailFilePathField = value;
                    this.OnPropertyChanged("MailFilePath");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 57)]
        public string MailFolderPath
        {
            get
            {
                return this.mailFolderPathField;
            }
            set
            {
                if ((this.mailFolderPathField != null))
                {
                    if ((mailFolderPathField.Equals(value) != true))
                    {
                        this.mailFolderPathField = value;
                        this.OnPropertyChanged("MailFolderPath");
                    }
                }
                else
                {
                    this.mailFolderPathField = value;
                    this.OnPropertyChanged("MailFolderPath");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 58)]
        public string TestMailHeader
        {
            get
            {
                return this.testMailHeaderField;
            }
            set
            {
                if ((this.testMailHeaderField != null))
                {
                    if ((testMailHeaderField.Equals(value) != true))
                    {
                        this.testMailHeaderField = value;
                        this.OnPropertyChanged("TestMailHeader");
                    }
                }
                else
                {
                    this.testMailHeaderField = value;
                    this.OnPropertyChanged("TestMailHeader");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 59)]
        public string TestMailBody
        {
            get
            {
                return this.testMailBodyField;
            }
            set
            {
                if ((this.testMailBodyField != null))
                {
                    if ((testMailBodyField.Equals(value) != true))
                    {
                        this.testMailBodyField = value;
                        this.OnPropertyChanged("TestMailBody");
                    }
                }
                else
                {
                    this.testMailBodyField = value;
                    this.OnPropertyChanged("TestMailBody");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 60)]
        public bool KeyManagerUse
        {
            get
            {
                return this.keyManagerUseField;
            }
            set
            {
                if ((keyManagerUseField.Equals(value) != true))
                {
                    this.keyManagerUseField = value;
                    this.OnPropertyChanged("KeyManagerUse");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 61)]
        public bool KeyManagerTest
        {
            get
            {
                return this.keyManagerTestField;
            }
            set
            {
                if ((keyManagerTestField.Equals(value) != true))
                {
                    this.keyManagerTestField = value;
                    this.OnPropertyChanged("KeyManagerTest");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 62)]
        public bool GetPrivateKeyRequest
        {
            get
            {
                return this.getPrivateKeyRequestField;
            }
            set
            {
                if ((getPrivateKeyRequestField.Equals(value) != true))
                {
                    this.getPrivateKeyRequestField = value;
                    this.OnPropertyChanged("GetPrivateKeyRequest");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 63)]
        public bool GetAllPrivateKeysForEmailRequest
        {
            get
            {
                return this.getAllPrivateKeysForEmailRequestField;
            }
            set
            {
                if ((getAllPrivateKeysForEmailRequestField.Equals(value) != true))
                {
                    this.getAllPrivateKeysForEmailRequestField = value;
                    this.OnPropertyChanged("GetAllPrivateKeysForEmailRequest");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 64)]
        public bool GetOrCreatePrivateKeyAdvancedRequest
        {
            get
            {
                return this.getOrCreatePrivateKeyAdvancedRequestField;
            }
            set
            {
                if ((getOrCreatePrivateKeyAdvancedRequestField.Equals(value) != true))
                {
                    this.getOrCreatePrivateKeyAdvancedRequestField = value;
                    this.OnPropertyChanged("GetOrCreatePrivateKeyAdvancedRequest");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 65)]
        public bool GetOrCreatePrivateKeyRequest
        {
            get
            {
                return this.getOrCreatePrivateKeyRequestField;
            }
            set
            {
                if ((getOrCreatePrivateKeyRequestField.Equals(value) != true))
                {
                    this.getOrCreatePrivateKeyRequestField = value;
                    this.OnPropertyChanged("GetOrCreatePrivateKeyRequest");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 66)]
        public bool Get509CertificateRequest
        {
            get
            {
                return this.get509CertificateRequestField;
            }
            set
            {
                if ((get509CertificateRequestField.Equals(value) != true))
                {
                    this.get509CertificateRequestField = value;
                    this.OnPropertyChanged("Get509CertificateRequest");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 67)]
        public bool ImportX509CertificateRequest
        {
            get
            {
                return this.importX509CertificateRequestField;
            }
            set
            {
                if ((importX509CertificateRequestField.Equals(value) != true))
                {
                    this.importX509CertificateRequestField = value;
                    this.OnPropertyChanged("ImportX509CertificateRequest");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 68)]
        public string ImportFromTenant
        {
            get
            {
                return this.importFromTenantField;
            }
            set
            {
                if ((this.importFromTenantField != null))
                {
                    if ((importFromTenantField.Equals(value) != true))
                    {
                        this.importFromTenantField = value;
                        this.OnPropertyChanged("ImportFromTenant");
                    }
                }
                else
                {
                    this.importFromTenantField = value;
                    this.OnPropertyChanged("ImportFromTenant");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 69)]
        public bool GetAllX509CertificatesForEmailRequest
        {
            get
            {
                return this.getAllX509CertificatesForEmailRequestField;
            }
            set
            {
                if ((getAllX509CertificatesForEmailRequestField.Equals(value) != true))
                {
                    this.getAllX509CertificatesForEmailRequestField = value;
                    this.OnPropertyChanged("GetAllX509CertificatesForEmailRequest");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 70)]
        public bool GetPrivateKeyFromEnvelopeRequest
        {
            get
            {
                return this.getPrivateKeyFromEnvelopeRequestField;
            }
            set
            {
                if ((getPrivateKeyFromEnvelopeRequestField.Equals(value) != true))
                {
                    this.getPrivateKeyFromEnvelopeRequestField = value;
                    this.OnPropertyChanged("GetPrivateKeyFromEnvelopeRequest");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 71)]
        public bool GetX509CertificateForVerificationBySignedDataRequest
        {
            get
            {
                return this.getX509CertificateForVerificationBySignedDataRequestField;
            }
            set
            {
                if ((getX509CertificateForVerificationBySignedDataRequestField.Equals(value) != true))
                {
                    this.getX509CertificateForVerificationBySignedDataRequestField = value;
                    this.OnPropertyChanged("GetX509CertificateForVerificationBySignedDataRequest");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 72)]
        public bool MakeCyclicCertsForAllTenantsSame
        {
            get
            {
                return this.makeCyclicCertsForAllTenantsSameField;
            }
            set
            {
                if ((makeCyclicCertsForAllTenantsSameField.Equals(value) != true))
                {
                    this.makeCyclicCertsForAllTenantsSameField = value;
                    this.OnPropertyChanged("MakeCyclicCertsForAllTenantsSame");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 73)]
        public string PrivateKeyType
        {
            get
            {
                return this.privateKeyTypeField;
            }
            set
            {
                if ((this.privateKeyTypeField != null))
                {
                    if ((privateKeyTypeField.Equals(value) != true))
                    {
                        this.privateKeyTypeField = value;
                        this.OnPropertyChanged("PrivateKeyType");
                    }
                }
                else
                {
                    this.privateKeyTypeField = value;
                    this.OnPropertyChanged("PrivateKeyType");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 74)]
        public string PublicKeyType
        {
            get
            {
                return this.publicKeyTypeField;
            }
            set
            {
                if ((this.publicKeyTypeField != null))
                {
                    if ((publicKeyTypeField.Equals(value) != true))
                    {
                        this.publicKeyTypeField = value;
                        this.OnPropertyChanged("PublicKeyType");
                    }
                }
                else
                {
                    this.publicKeyTypeField = value;
                    this.OnPropertyChanged("PublicKeyType");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute("Tenants", Order = 75)]
        public ObservableCollection<ServerSchemaTenants> Tenants
        {
            get
            {
                if ((this.tenantsField == null))
                {
                    this.tenantsField = new ObservableCollection<ServerSchemaTenants>();
                }
                return this.tenantsField;
            }
            set
            {
                if ((this.tenantsField != null))
                {
                    if ((tenantsField.Equals(value) != true))
                    {
                        this.tenantsField = value;
                        this.OnPropertyChanged("Tenants");
                    }
                }
                else
                {
                    this.tenantsField = value;
                    this.OnPropertyChanged("Tenants");
                }
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://tempuri.org/MailConfig.xsd")]
    public partial class ServerSchemaHeader : EntityBase<ServerSchemaHeader>
    {

        private string nameField;

        private string valueField;

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                if ((this.nameField != null))
                {
                    if ((nameField.Equals(value) != true))
                    {
                        this.nameField = value;
                        this.OnPropertyChanged("Name");
                    }
                }
                else
                {
                    this.nameField = value;
                    this.OnPropertyChanged("Name");
                }
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                if ((this.valueField != null))
                {
                    if ((valueField.Equals(value) != true))
                    {
                        this.valueField = value;
                        this.OnPropertyChanged("Value");
                    }
                }
                else
                {
                    this.valueField = value;
                    this.OnPropertyChanged("Value");
                }
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://tempuri.org/MailConfig.xsd")]
    public partial class ServerSchemaSubject : EntityBase<ServerSchemaSubject>
    {

        private string subjectExtensionValueField;

        private bool subjectNoneField;

        private bool subjectExtentAtBeginField;

        private bool subjectExtentAtEndField;

        private bool subjectMailCountField;

        private bool subjectMailNameField;

        private bool subjectMailNameBeginField;

        private bool subjectMailNameEndField;

        private bool subjectMailNameReplaceField;

        private string nameField;

        private string valueField;

        public ServerSchemaSubject()
        {
            this.subjectNoneField = true;
            this.subjectExtentAtBeginField = false;
            this.subjectExtentAtEndField = false;
            this.subjectMailCountField = false;
            this.subjectMailNameField = false;
            this.subjectMailNameBeginField = true;
            this.subjectMailNameEndField = false;
            this.subjectMailNameReplaceField = false;
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public string SubjectExtensionValue
        {
            get
            {
                return this.subjectExtensionValueField;
            }
            set
            {
                if ((this.subjectExtensionValueField != null))
                {
                    if ((subjectExtensionValueField.Equals(value) != true))
                    {
                        this.subjectExtensionValueField = value;
                        this.OnPropertyChanged("SubjectExtensionValue");
                    }
                }
                else
                {
                    this.subjectExtensionValueField = value;
                    this.OnPropertyChanged("SubjectExtensionValue");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public bool SubjectNone
        {
            get
            {
                return this.subjectNoneField;
            }
            set
            {
                if ((subjectNoneField.Equals(value) != true))
                {
                    this.subjectNoneField = value;
                    this.OnPropertyChanged("SubjectNone");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public bool SubjectExtentAtBegin
        {
            get
            {
                return this.subjectExtentAtBeginField;
            }
            set
            {
                if ((subjectExtentAtBeginField.Equals(value) != true))
                {
                    this.subjectExtentAtBeginField = value;
                    this.OnPropertyChanged("SubjectExtentAtBegin");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
        public bool SubjectExtentAtEnd
        {
            get
            {
                return this.subjectExtentAtEndField;
            }
            set
            {
                if ((subjectExtentAtEndField.Equals(value) != true))
                {
                    this.subjectExtentAtEndField = value;
                    this.OnPropertyChanged("SubjectExtentAtEnd");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 4)]
        public bool SubjectMailCount
        {
            get
            {
                return this.subjectMailCountField;
            }
            set
            {
                if ((subjectMailCountField.Equals(value) != true))
                {
                    this.subjectMailCountField = value;
                    this.OnPropertyChanged("SubjectMailCount");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 5)]
        public bool SubjectMailName
        {
            get
            {
                return this.subjectMailNameField;
            }
            set
            {
                if ((subjectMailNameField.Equals(value) != true))
                {
                    this.subjectMailNameField = value;
                    this.OnPropertyChanged("SubjectMailName");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 6)]
        public bool SubjectMailNameBegin
        {
            get
            {
                return this.subjectMailNameBeginField;
            }
            set
            {
                if ((subjectMailNameBeginField.Equals(value) != true))
                {
                    this.subjectMailNameBeginField = value;
                    this.OnPropertyChanged("SubjectMailNameBegin");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 7)]
        public bool SubjectMailNameEnd
        {
            get
            {
                return this.subjectMailNameEndField;
            }
            set
            {
                if ((subjectMailNameEndField.Equals(value) != true))
                {
                    this.subjectMailNameEndField = value;
                    this.OnPropertyChanged("SubjectMailNameEnd");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 8)]
        public bool SubjectMailNameReplace
        {
            get
            {
                return this.subjectMailNameReplaceField;
            }
            set
            {
                if ((subjectMailNameReplaceField.Equals(value) != true))
                {
                    this.subjectMailNameReplaceField = value;
                    this.OnPropertyChanged("SubjectMailNameReplace");
                }
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                if ((this.nameField != null))
                {
                    if ((nameField.Equals(value) != true))
                    {
                        this.nameField = value;
                        this.OnPropertyChanged("Name");
                    }
                }
                else
                {
                    this.nameField = value;
                    this.OnPropertyChanged("Name");
                }
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                if ((this.valueField != null))
                {
                    if ((valueField.Equals(value) != true))
                    {
                        this.valueField = value;
                        this.OnPropertyChanged("Value");
                    }
                }
                else
                {
                    this.valueField = value;
                    this.OnPropertyChanged("Value");
                }
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://tempuri.org/MailConfig.xsd")]
    public partial class ServerSchemaTenants : EntityBase<ServerSchemaTenants>
    {

        private string tenantDisplayNameField;

        private string tenantValueField;

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string TenantDisplayName
        {
            get
            {
                return this.tenantDisplayNameField;
            }
            set
            {
                if ((this.tenantDisplayNameField != null))
                {
                    if ((tenantDisplayNameField.Equals(value) != true))
                    {
                        this.tenantDisplayNameField = value;
                        this.OnPropertyChanged("TenantDisplayName");
                    }
                }
                else
                {
                    this.tenantDisplayNameField = value;
                    this.OnPropertyChanged("TenantDisplayName");
                }
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string TenantValue
        {
            get
            {
                return this.tenantValueField;
            }
            set
            {
                if ((this.tenantValueField != null))
                {
                    if ((tenantValueField.Equals(value) != true))
                    {
                        this.tenantValueField = value;
                        this.OnPropertyChanged("TenantValue");
                    }
                }
                else
                {
                    this.tenantValueField = value;
                    this.OnPropertyChanged("TenantValue");
                }
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://tempuri.org/MailConfig.xsd")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://tempuri.org/MailConfig.xsd", IsNullable = true)]
    public partial class Servers : EntityBase<Servers>
    {

        private ObservableCollection<ServerSchema> serverSchemaField;

        private bool oneServerField;

        public Servers()
        {
            this.oneServerField = true;
        }

        [System.Xml.Serialization.XmlElementAttribute("ServerSchema", Order = 0)]
        public ObservableCollection<ServerSchema> ServerSchema
        {
            get
            {
                if ((this.serverSchemaField == null))
                {
                    this.serverSchemaField = new ObservableCollection<ServerSchema>();
                }
                return this.serverSchemaField;
            }
            set
            {
                if ((this.serverSchemaField != null))
                {
                    if ((serverSchemaField.Equals(value) != true))
                    {
                        this.serverSchemaField = value;
                        this.OnPropertyChanged("ServerSchema");
                    }
                }
                else
                {
                    this.serverSchemaField = value;
                    this.OnPropertyChanged("ServerSchema");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public bool OneServer
        {
            get
            {
                return this.oneServerField;
            }
            set
            {
                if ((oneServerField.Equals(value) != true))
                {
                    this.oneServerField = value;
                    this.OnPropertyChanged("OneServer");
                }
            }
        }
    }
}
