#pragma checksum "..\..\..\..\UserControls\ServerControl.xaml" "{406ea660-64cf-4c82-b6f0-42d48172a799}" "CF76225F2C8A26D31836C37122F99E6E"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using MailSendWPF.UserControls;
using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace MailSendWPF.UserControls {
    
    
    /// <summary>
    /// ServerControl
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
    public partial class ServerControl : System.Windows.Controls.UserControl, System.Windows.Markup.IComponentConnector {
        
        
        #line 8 "..\..\..\..\UserControls\ServerControl.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal MailSendWPF.UserControls.ServerControl serverControl;
        
        #line default
        #line hidden
        
        
        #line 10 "..\..\..\..\UserControls\ServerControl.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border outerBorder;
        
        #line default
        #line hidden
        
        
        #line 11 "..\..\..\..\UserControls\ServerControl.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.StackPanel outputStackPanel;
        
        #line default
        #line hidden
        
        
        #line 12 "..\..\..\..\UserControls\ServerControl.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.StackPanel outerStackPanel;
        
        #line default
        #line hidden
        
        
        #line 14 "..\..\..\..\UserControls\ServerControl.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal MailSendWPF.UserControls.StartMailPanel startMailPanel1;
        
        #line default
        #line hidden
        
        
        #line 17 "..\..\..\..\UserControls\ServerControl.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal MailSendWPF.UserControls.ResToMailPanel resToMailPanel1;
        
        #line default
        #line hidden
        
        
        #line 19 "..\..\..\..\UserControls\ServerControl.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal MailSendWPF.UserControls.MailsPanel mailsPanel;
        
        #line default
        #line hidden
        
        
        #line 24 "..\..\..\..\UserControls\ServerControl.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ListBox mailingOutput;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/MailSendWPF;component/usercontrols/servercontrol.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\..\..\UserControls\ServerControl.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal System.Delegate _CreateDelegate(System.Type delegateType, string handler) {
            return System.Delegate.CreateDelegate(delegateType, this, handler);
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.serverControl = ((MailSendWPF.UserControls.ServerControl)(target));
            return;
            case 2:
            this.outerBorder = ((System.Windows.Controls.Border)(target));
            return;
            case 3:
            this.outputStackPanel = ((System.Windows.Controls.StackPanel)(target));
            return;
            case 4:
            this.outerStackPanel = ((System.Windows.Controls.StackPanel)(target));
            return;
            case 5:
            this.startMailPanel1 = ((MailSendWPF.UserControls.StartMailPanel)(target));
            return;
            case 6:
            this.resToMailPanel1 = ((MailSendWPF.UserControls.ResToMailPanel)(target));
            return;
            case 7:
            this.mailsPanel = ((MailSendWPF.UserControls.MailsPanel)(target));
            return;
            case 8:
            this.mailingOutput = ((System.Windows.Controls.ListBox)(target));
            return;
            }
            this._contentLoaded = true;
        }
    }
}

